/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        SPEECH_RECOGNITION: 'Speech Recognition',
        YUNYININIT: 'Initialize speech recognition module %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Recognized %1 command',
        YUNYINQINGCHU: 'Clear recognition results',
        BOXIAOSHU: 'Broadcast decimal %1',
        BOZHENGSHU: 'Broadcast integer %1',
        YUYINBOBAO: 'Broadcast %1',
        SOFT_SERIAL: 'Soft Serial',
        HARD_SERIAL: 'Hard Serial',
        TURN_ON_LIGHT: 'Turn on the light',
        TURN_OFF_LIGHT: 'Turn off the light',
        INCREASE_BRIGHTNESS: 'Brighten up',
        DECREASE_BRIGHTNESS: 'Dim down',
        TURN_ON_FAN: 'Turn on the fan',
        TURN_OFF_FAN: 'Turn off the fan',
        INCREASE_WIND_SPEED: 'make it windier',
        DECREASE_WIND_SPEED: 'make it less windy',
        WATER_PLANTS: 'please water',
        STOP_WATERING: 'Stop watering',
        PLAY_MUSIC: 'Play music',
        STOP_MUSIC: 'Stop music',
        TURN_ON_RED_LIGHT: 'Turn on the red light',
        TURN_OFF_RED_LIGHT: 'Turn off the red light',
        TURN_ON_GREEN_LIGHT: 'Turn on the green light',
        TURN_OFF_GREEN_LIGHT: 'Turn off the green light',
        TURN_ON_BLUE_LIGHT: 'Turn on the blue light',
        TURN_OFF_BLUE_LIGHT: 'Turn off the blue light',
        TURN_ON_LED_MATRIX: 'turn on the lattice',
        TURN_OFF_LED_MATRIX: 'turn off the lattice',
        SOMEONE_IS_APPROACHING: 'someone is here',
        PERSON_IS_MOVING_AWAY: 'no one is here',
        ITS_RAINING: 'it is raining',
        STOP_RAIN: 'the rain stopped',
        MOVE_FORWARD: 'Move forward',
        MOVE_BACKWARD: 'Move backward',
        TURN_LEFT: 'Turn left',
        TURN_RIGHT: 'Turn right',
        FOLLOW_TRACK: 'tracking',
        FOLLOW_PERSON: 'following',
        AVOID_OBSTACLE: 'obstacle avoidance',
        SEEK_LIGHT: 'light seeking',
        STOP: 'Stop',
        START_FEEDING: 'Start feeding',
        STOP_FEEDING: 'Stop feeding',
        TURN_ON_COLORFUL_LIGHT: 'turn on the RGB light',
        TURN_OFF_COLORFUL_LIGHT: 'turn off the RGB light',
        TURN_ON_BUZZER: 'Turn on buzzer',
        TURN_OFF_BUZZER: 'Turn off buzzer',
        INCREASE_VOLUME: 'Increase volume',
        DECREASE_VOLUME: 'Decrease volume',
        MAXIMUM_VOLUME: 'Maximum volume',
        MEDIUM_VOLUME: 'Medium volume',
        MINIMUM_VOLUME: 'Minimum volume',
        INCREASE_SERVO_ANGLE: 'Increase servo angle',
        DECREASE_SERVO_ANGLE: 'Decrease servo angle',
        CURRENT_TEMPERATURE: 'What is the current temperature?',
        CURRENT_HUMIDITY: 'What is the current humidity?',
        CURRENT_RAINFALL_AMOUNT: 'What is the current rainfall?',
        CURRENT_LIGHT_INTENSITY: 'What is the current light intensity?',
        CURRENT_SOIL_MOISTURE: 'What is the current soil moisture?',
        CURRENT_WATER_LEVEL: 'What is the current water level?',
        WHAT_TIME_IS_IT: 'What time is it?',
        CURRENT_DISTANCE: 'What is the current distance?',
        TURN_ON: 'Power on',
        TURN_OFF: 'Power off',
        OPEN_WINDOW: 'Open the window',
        CLOSE_WINDOW: 'Close the window',
        OPEN_DOOR: 'Open the door',
        CLOSE_DOOR: 'Close the door',
        FLAG_UP: 'Raise the flag',
        FLAG_DOWN: 'Fall the flag',
        CURTAIN_ON: 'Open the curtain',
        CURTAIN_OFF: 'Close the curtain',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'What is the current total concentration of volatile organic compounds?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'What is the current concentration of carbon dioxide?',
        CURRENT_AIR_QUALITY_INDEX: 'What is the current air quality index?',
        Approach_Alar: 'If someone approaches, please sound the alarm',

        CURRENT_TEMPERATURE_IS: 'current temperature is',
        DEGREES: 'degrees',
        CURRENT_RAINFALL_PERCENTAGE: 'current rainfall is percent',
        CURRENT_HUMIDITY_PERCENTAGE: 'current humidity is percent',
        CURRENT_LIGHT_INTENSITY_IS: 'current light intensity is',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'current soil moisture is percent',
        CURRENT_WATER_LEVEL_IS: 'current water level is',
        CURRENT_BEIJING_TIME: 'current time in Beijing is',
        CURRENT_DISTANCE_IS: 'current distance is',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'second',
        ROUND_HOUR: 'o\'clock',
        MILLILITERS: 'milliliters',
        MILLIMETERS: 'millimeters',
        CENTIMETERS: 'centimeters',
        METERS: 'meters',
        KILOMETERS: 'kilometers',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'current total volatile organic compound concentration is parts per billion',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'current concentration of carbon dioxide is parts per million',
        CURRENT_AIR_QUALITY_INDEX_IS: 'current air quality index is',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        SPEECH_RECOGNITION: 'Spracherkennung',
        YUNYININIT: 'Spracherkennungsmodul %1 RX %2 TX %3 initialisieren',
        YUNYINSHIBIE: 'Befehl %1 erkannt',
        YUNYINQINGCHU: 'Erkennungsergebnisse löschen',
        BOXIAOSHU: 'Dezimal %1 ansagen',
        BOZHENGSHU: 'Ganzzahl %1 ansagen',
        YUYINBOBAO: 'Ansage %1',
        SOFT_SERIAL: 'Weiche serielle Schnittstelle',
        HARD_SERIAL: 'Harte serielle Schnittstelle',
        TURN_ON_LIGHT: 'Licht einschalten',
        TURN_OFF_LIGHT: 'Licht ausschalten',
        INCREASE_BRIGHTNESS: 'Helligkeit erhöhen',
        DECREASE_BRIGHTNESS: 'Helligkeit verringern',
        TURN_ON_FAN: 'Lüfter einschalten',
        TURN_OFF_FAN: 'Lüfter ausschalten',
        INCREASE_WIND_SPEED: 'Windgeschwindigkeit erhöhen',
        DECREASE_WIND_SPEED: 'Windgeschwindigkeit verringern',
        WATER_PLANTS: 'Pflanzen gießen',
        STOP_WATERING: 'Gießen stoppen',
        PLAY_MUSIC: 'Musik abspielen',
        STOP_MUSIC: 'Musik stoppen',
        TURN_ON_RED_LIGHT: 'Rotes Licht einschalten',
        TURN_OFF_RED_LIGHT: 'Rotes Licht ausschalten',
        TURN_ON_GREEN_LIGHT: 'Grünes Licht einschalten',
        TURN_OFF_GREEN_LIGHT: 'Grünes Licht ausschalten',
        TURN_ON_BLUE_LIGHT: 'Blaues Licht einschalten',
        TURN_OFF_BLUE_LIGHT: 'Blaues Licht ausschalten',
        TURN_ON_LED_MATRIX: 'LED-Matrix einschalten',
        TURN_OFF_LED_MATRIX: 'LED-Matrix ausschalten',
        SOMEONE_IS_APPROACHING: 'Jemand nähert sich',
        PERSON_IS_MOVING_AWAY: 'Person entfernt sich',
        ITS_RAINING: 'Es regnet',
        STOP_RAIN: 'Regen gestoppt',
        MOVE_FORWARD: 'Vorwärts bewegen',
        MOVE_BACKWARD: 'Rückwärts bewegen',
        TURN_LEFT: 'Nach links drehen',
        TURN_RIGHT: 'Nach rechts drehen',
        FOLLOW_TRACK: 'Spur folgen',
        FOLLOW_PERSON: 'Person folgen',
        AVOID_OBSTACLE: 'Hindernis vermeiden',
        SEEK_LIGHT: 'Licht suchen',
        STOP: 'Stoppen',
        START_FEEDING: 'Füttern starten',
        STOP_FEEDING: 'Füttern stoppen',
        TURN_ON_COLORFUL_LIGHT: 'Buntes Licht einschalten',
        TURN_OFF_COLORFUL_LIGHT: 'Buntes Licht ausschalten',
        TURN_ON_BUZZER: 'Summer einschalten',
        TURN_OFF_BUZZER: 'Summer ausschalten',
        INCREASE_VOLUME: 'Lautstärke erhöhen',
        DECREASE_VOLUME: 'Lautstärke verringern',
        MAXIMUM_VOLUME: 'Maximale Lautstärke',
        MEDIUM_VOLUME: 'Mittlere Lautstärke',
        MINIMUM_VOLUME: 'Minimale Lautstärke',
        INCREASE_SERVO_ANGLE: 'Servo-Winkel erhöhen',
        DECREASE_SERVO_ANGLE: 'Servo-Winkel verringern',
        CURRENT_TEMPERATURE: 'Wie hoch ist die aktuelle Temperatur?',
        CURRENT_HUMIDITY: 'Wie hoch ist die aktuelle Feuchtigkeit?',
        CURRENT_RAINFALL_AMOUNT: 'Wie hoch ist der aktuelle Niederschlagsmenge?',
        CURRENT_LIGHT_INTENSITY: 'Wie hoch ist die aktuelle Lichtintensität?',
        CURRENT_SOIL_MOISTURE: 'Wie hoch ist die aktuelle Bodenfeuchtigkeit?',
        CURRENT_WATER_LEVEL: 'Wie hoch ist der aktuelle Wasserstand?',
        WHAT_TIME_IS_IT: 'Wie spät ist es?',
        CURRENT_DISTANCE: 'Wie groß ist der aktuelle Abstand?',
        TURN_ON: 'Einschalten',
        TURN_OFF: 'Ausschalten',
        OPEN_WINDOW: 'Öffne das Fenster',
        CLOSE_WINDOW: 'Schließe das Fenster',
        OPEN_DOOR: 'Öffne die Tür',
        CLOSE_DOOR: 'Schließe die Tür',
        FLAG_UP: 'Flagge hissen',
        FLAG_DOWN: 'Flagge einholen',
        CURTAIN_ON: 'Die Vorhänge öffnen',
        CURTAIN_OFF: 'Die Gardine zuziehen',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'Wie hoch ist die aktuelle Gesamtkonzentration flüchtiger organischer Verbindungen?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'Wie hoch ist die aktuelle Kohlendioxidkonzentration?',
        CURRENT_AIR_QUALITY_INDEX: 'Wie hoch ist der aktuelle Luftqualitätsindex?',

        Approach_Alar: 'Wenn sich jemand nähert, bitte Alarm auslösen',
        CURRENT_TEMPERATURE_IS: 'Aktuelle Temperatur beträgt',
        DEGREES: 'Grad',
        CURRENT_RAINFALL_PERCENTAGE: 'Aktueller Niederschlag beträgt Prozent',
        CURRENT_HUMIDITY_PERCENTAGE: 'Aktuelle Feuchtigkeit beträgt Prozent',
        CURRENT_LIGHT_INTENSITY_IS: 'Aktuelle Lichtintensität beträgt',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'Aktuelle Bodenfeuchtigkeit beträgt Prozent',
        CURRENT_WATER_LEVEL_IS: 'Aktueller Wasserstand beträgt',
        CURRENT_BEIJING_TIME: 'Aktuelle Zeit in Peking ist',
        CURRENT_DISTANCE_IS: 'Aktueller Abstand beträgt',
        POINT: 'Punkt',
        MINUTE: 'Minute',
        SECOND: 'Sekunde',
        ROUND_HOUR: 'Uhr',
        MILLILITERS: 'Milliliter',
        MILLIMETERS: 'Millimeter',
        CENTIMETERS: 'Zentimeter',
        METERS: 'Meter',
        KILOMETERS: 'Kilometer',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'Aktuelle Konzentration der gesamten flüchtigen organischen Verbindungen beträgt Teile pro Milliarde',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'Aktuelle Kohlenstoffdioxid-Konzentration beträgt Teile pro Million',
        CURRENT_AIR_QUALITY_INDEX_IS: 'Aktuelle Luftqualitätsindex beträgt',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        SPEECH_RECOGNITION: 'Reconocimiento de Voz',
        YUNYININIT: 'Inicializar el módulo de reconocimiento de voz %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Comando %1 reconocido',
        YUNYINQINGCHU: 'Limpiar resultados de reconocimiento',
        BOXIAOSHU: 'Anunciar decimal %1',
        BOZHENGSHU: 'Anunciar número entero %1',
        YUYINBOBAO: 'Anunciar %1',
        SOFT_SERIAL: 'Serial suave',
        HARD_SERIAL: 'Serial duro',
        TURN_ON_LIGHT: 'Enciende la luz',
        TURN_OFF_LIGHT: 'Apaga la luz',
        INCREASE_BRIGHTNESS: 'Aumenta el brillo',
        DECREASE_BRIGHTNESS: 'Disminuye el brillo',
        TURN_ON_FAN: 'Enciende el ventilador',
        TURN_OFF_FAN: 'Apaga el ventilador',
        INCREASE_WIND_SPEED: 'Aumenta la velocidad del viento',
        DECREASE_WIND_SPEED: 'Disminuye la velocidad del viento',
        WATER_PLANTS: 'Riega las plantas',
        STOP_WATERING: 'Detén el riego',
        PLAY_MUSIC: 'Reproduce música',
        STOP_MUSIC: 'Detén la música',
        TURN_ON_RED_LIGHT: 'Enciende la luz roja',
        TURN_OFF_RED_LIGHT: 'Apaga la luz roja',
        TURN_ON_GREEN_LIGHT: 'Enciende la luz verde',
        TURN_OFF_GREEN_LIGHT: 'Apaga la luz verde',
        TURN_ON_BLUE_LIGHT: 'Enciende la luz azul',
        TURN_OFF_BLUE_LIGHT: 'Apaga la luz azul',
        TURN_ON_LED_MATRIX: 'Enciende la matriz LED',
        TURN_OFF_LED_MATRIX: 'Apaga la matriz LED',
        SOMEONE_IS_APPROACHING: 'Alguien se acerca',
        PERSON_IS_MOVING_AWAY: 'La persona se aleja',
        ITS_RAINING: 'Está lloviendo',
        STOP_RAIN: 'La lluvia se detiene',
        MOVE_FORWARD: 'Avanza',
        MOVE_BACKWARD: 'Retrocede',
        TURN_LEFT: 'Gira a la izquierda',
        TURN_RIGHT: 'Gira a la derecha',
        FOLLOW_TRACK: 'Sigue la pista',
        FOLLOW_PERSON: 'Sigue a la persona',
        AVOID_OBSTACLE: 'Evita obstáculos',
        SEEK_LIGHT: 'Busca luz',
        STOP: 'Detente',
        START_FEEDING: 'Comienza a alimentar',
        STOP_FEEDING: 'Detén la alimentación',
        TURN_ON_COLORFUL_LIGHT: 'Enciende la luz colorida',
        TURN_OFF_COLORFUL_LIGHT: 'Apaga la luz colorida',
        TURN_ON_BUZZER: 'Enciende el zumbador',
        TURN_OFF_BUZZER: 'Apaga el zumbador',
        INCREASE_VOLUME: 'Aumenta el volumen',
        DECREASE_VOLUME: 'Disminuye el volumen',
        MAXIMUM_VOLUME: 'Volumen máximo',
        MEDIUM_VOLUME: 'Volumen medio',
        MINIMUM_VOLUME: 'Volumen mínimo',
        INCREASE_SERVO_ANGLE: 'Aumenta el ángulo del servo',
        DECREASE_SERVO_ANGLE: 'Disminuye el ángulo del servo',
        CURRENT_TEMPERATURE: '¿Cuál es la temperatura actual?',
        CURRENT_HUMIDITY: '¿Cuál es la humedad actual?',
        CURRENT_RAINFALL_AMOUNT: '¿Cuál es la cantidad de lluvia actual?',
        CURRENT_LIGHT_INTENSITY: '¿Cuál es la intensidad de luz actual?',
        CURRENT_SOIL_MOISTURE: '¿Cuál es la humedad del suelo actual?',
        CURRENT_WATER_LEVEL: '¿Cuál es el nivel de agua actual?',
        WHAT_TIME_IS_IT: '¿Qué hora es?',
        CURRENT_DISTANCE: '¿Cuál es la distancia actual?',
        TURN_ON: 'Enciende',
        TURN_OFF: 'Apaga',
        OPEN_WINDOW: 'Abrir la ventana',
        CLOSE_WINDOW: 'Cerrar la ventana',
        OPEN_DOOR: 'Abrir la puerta',
        CLOSE_DOOR: 'Cerrar la puerta',
        FLAG_UP: 'Izar la bandera',
        FLAG_DOWN: 'Arriar la bandera',
        CURTAIN_ON: 'Abre la cortina',
        CURTAIN_OFF: 'Cierra la cortina',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: '¿Cuál es la concentración actual de compuestos orgánicos volátiles totales?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: '¿Cuál es la concentración actual de dióxido de carbono?',
        CURRENT_AIR_QUALITY_INDEX: '¿Cuál es el índice de calidad del aire actual?',

        Approach_Alar: 'Si alguien se acerca, por favor suene la alarma',
        CURRENT_TEMPERATURE_IS: 'La temperatura actual es',
        DEGREES: 'grados',
        CURRENT_RAINFALL_PERCENTAGE: 'La cantidad de lluvia actual es de porcentaje',
        CURRENT_HUMIDITY_PERCENTAGE: 'La humedad actual es de porcentaje',
        CURRENT_LIGHT_INTENSITY_IS: 'La intensidad de luz actual es',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'La humedad del suelo actual es de porcentaje',
        CURRENT_WATER_LEVEL_IS: 'El nivel de agua actual es',
        CURRENT_BEIJING_TIME: 'La hora actual en Pekín es',
        CURRENT_DISTANCE_IS: 'La distancia actual es',
        POINT: 'punto',
        MINUTE: 'minuto',
        SECOND: 'segundo',
        ROUND_HOUR: 'en punto',
        MILLILITERS: 'mililitros',
        MILLIMETERS: 'milímetros',
        CENTIMETERS: 'centímetros',
        METERS: 'metros',
        KILOMETERS: 'kilómetros',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'La concentración actual de compuestos orgánicos volátiles totales es de partes por mil millones',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'La concentración actual de dióxido de carbono es de partes por millón',
        CURRENT_AIR_QUALITY_INDEX_IS: 'El índice de calidad del aire actual es de',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        SPEECH_RECOGNITION: 'Reconnaissance Vocale',
        YUNYININIT: 'Initialiser le module de reconnaissance vocale %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Commande %1 reconnue',
        YUNYINQINGCHU: 'Effacer les résultats de reconnaissance',
        BOXIAOSHU: 'Annoncer le décimal %1',
        BOZHENGSHU: 'Annoncer le nombre entier %1',
        YUYINBOBAO: 'Annoncer %1',
        SOFT_SERIAL: 'Série logicielle',
        HARD_SERIAL: 'Série matérielle',
        TURN_ON_LIGHT: 'Allumer la lumière',
        TURN_OFF_LIGHT: 'Éteindre la lumière',
        INCREASE_BRIGHTNESS: 'Augmenter la luminosité',
        DECREASE_BRIGHTNESS: 'Diminuer la luminosité',
        TURN_ON_FAN: 'Allumer le ventilateur',
        TURN_OFF_FAN: 'Éteindre le ventilateur',
        INCREASE_WIND_SPEED: 'Augmenter la vitesse du vent',
        DECREASE_WIND_SPEED: 'Diminuer la vitesse du vent',
        WATER_PLANTS: 'Arroser les plantes',
        STOP_WATERING: 'Arrêter l\'arrosage',
        PLAY_MUSIC: 'Jouer de la musique',
        STOP_MUSIC: 'Arrêter la musique',
        TURN_ON_RED_LIGHT: 'Allumer la lumière rouge',
        TURN_OFF_RED_LIGHT: 'Éteindre la lumière rouge',
        TURN_ON_GREEN_LIGHT: 'Allumer la lumière verte',
        TURN_OFF_GREEN_LIGHT: 'Éteindre la lumière verte',
        TURN_ON_BLUE_LIGHT: 'Allumer la lumière bleue',
        TURN_OFF_BLUE_LIGHT: 'Éteindre la lumière bleue',
        TURN_ON_LED_MATRIX: 'Allumer la matrice LED',
        TURN_OFF_LED_MATRIX: 'Éteindre la matrice LED',
        SOMEONE_IS_APPROACHING: 'Quelqu\'un s\'approche',
        PERSON_IS_MOVING_AWAY: 'La personne s\'éloigne',
        ITS_RAINING: 'Il pleut',
        STOP_RAIN: 'La pluie s\'arrête',
        MOVE_FORWARD: 'Avancer',
        MOVE_BACKWARD: 'Reculer',
        TURN_LEFT: 'Tourner à gauche',
        TURN_RIGHT: 'Tourner à droite',
        FOLLOW_TRACK: 'Suivre la piste',
        FOLLOW_PERSON: 'Suivre la personne',
        AVOID_OBSTACLE: 'Éviter les obstacles',
        SEEK_LIGHT: 'Chercher la lumière',
        STOP: 'Arrêter',
        START_FEEDING: 'Commencer à nourrir',
        STOP_FEEDING: 'Arrêter de nourrir',
        TURN_ON_COLORFUL_LIGHT: 'Allumer la lumière colorée',
        TURN_OFF_COLORFUL_LIGHT: 'Éteindre la lumière colorée',
        TURN_ON_BUZZER: 'Allumer le buzzer',
        TURN_OFF_BUZZER: 'Éteindre le buzzer',
        INCREASE_VOLUME: 'Augmenter le volume',
        DECREASE_VOLUME: 'Diminuer le volume',
        MAXIMUM_VOLUME: 'Volume maximum',
        MEDIUM_VOLUME: 'Volume moyen',
        MINIMUM_VOLUME: 'Volume minimum',
        INCREASE_SERVO_ANGLE: 'Augmenter l\'angle du servo',
        DECREASE_SERVO_ANGLE: 'Diminuer l\'angle du servo',
        CURRENT_TEMPERATURE: 'Quelle est la température actuelle ?',
        CURRENT_HUMIDITY: 'Quelle est l\'humidité actuelle ?',
        CURRENT_RAINFALL_AMOUNT: 'Quelle est la quantité de pluie actuelle ?',
        CURRENT_LIGHT_INTENSITY: 'Quelle est l\'intensité lumineuse actuelle ?',
        CURRENT_SOIL_MOISTURE: 'Quelle est l\'humidité du sol actuelle ?',
        CURRENT_WATER_LEVEL: 'Quel est le niveau d\'eau actuel ?',
        WHAT_TIME_IS_IT: 'Quelle heure est-il ?',
        CURRENT_DISTANCE: 'Quelle est la distance actuelle ?',
        TURN_ON: 'Allumer',
        TURN_OFF: 'Éteindre',
        OPEN_WINDOW: 'Ouvrir la fenêtre',
        CLOSE_WINDOW: 'Fermer la fenêtre',
        OPEN_DOOR: 'Ouvrir la porte',
        CLOSE_DOOR: 'Fermer la porte',
        FLAG_UP: 'hisser la drapeau',
        FLAG_DOWN: 'ammener la drapeau',
        CURTAIN_ON: 'ouvrir la rideau',
        CURTAIN_OFF: 'fermer la rideau',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'Quelle est la concentration actuelle de composés organiques volatils totaux?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'Quelle est la concentration actuelle de dioxyde de carbone ?',
        CURRENT_AIR_QUALITY_INDEX: 'Quel est l’indice actuel de la qualité de l’air ?',

        Approach_Alar: "Si quelqu'un s'approche, veuillez déclencher l'alarme",
        CURRENT_TEMPERATURE_IS: 'La température actuelle est',
        DEGREES: 'degrés',
        CURRENT_RAINFALL_PERCENTAGE: 'La quantité de pluie actuelle est de pour cent',
        CURRENT_HUMIDITY_PERCENTAGE: 'L\'humidité actuelle est de pour cent',
        CURRENT_LIGHT_INTENSITY_IS: 'L\'intensité lumineuse actuelle est',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'L\'humidité du sol actuelle est de pour cent',
        CURRENT_WATER_LEVEL_IS: 'Le niveau d\'eau actuel est',
        CURRENT_BEIJING_TIME: 'L\'heure actuelle à Pékin est',
        CURRENT_DISTANCE_IS: 'La distance actuelle est',
        POINT: 'point',
        MINUTE: 'minute',
        SECOND: 'seconde',
        ROUND_HOUR: 'pile',
        MILLILITERS: 'millilitres',
        MILLIMETERS: 'millimètres',
        CENTIMETERS: 'centimètres',
        METERS: 'mètres',
        KILOMETERS: 'kilomètres',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'La concentration actuelle de composés organiques volatils totaux est de parties par milliard',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'La concentration actuelle de dioxyde de carbone est de parties par million',
        CURRENT_AIR_QUALITY_INDEX_IS: 'L’indice actuel de la qualité de l’air est de',
    });
Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        SPEECH_RECOGNITION: '音声認識',
        YUNYININIT: '音声認識モジュール %1 RX %2 TX %3 を初期化',
        YUNYINSHIBIE: '%1 コマンドを認識',
        YUNYINQINGCHU: '認識結果をクリア',
        BOXIAOSHU: '小数 %1 を読み上げ',
        BOZHENGSHU: '整数 %1 を読み上げ',
        YUYINBOBAO: '%1 を読み上げ',
        SOFT_SERIAL: 'ソフトシリアル',
        HARD_SERIAL: 'ハードシリアル',
        TURN_ON_LIGHT: 'ライトをつける',
        TURN_OFF_LIGHT: 'ライトを消す',
        INCREASE_BRIGHTNESS: '明るくする',
        DECREASE_BRIGHTNESS: '暗くする',
        TURN_ON_FAN: '扇風機をつける',
        TURN_OFF_FAN: '扇風機を消す',
        INCREASE_WIND_SPEED: '風を強くする',
        DECREASE_WIND_SPEED: '風を弱くする',
        WATER_PLANTS: '植物に水をやる',
        STOP_WATERING: '水やりを止める',
        PLAY_MUSIC: '音楽を再生',
        STOP_MUSIC: '音楽を止める',
        TURN_ON_RED_LIGHT: '赤いライトをつける',
        TURN_OFF_RED_LIGHT: '赤いライトを消す',
        TURN_ON_GREEN_LIGHT: '緑のライトをつける',
        TURN_OFF_GREEN_LIGHT: '緑のライトを消す',
        TURN_ON_BLUE_LIGHT: '青いライトをつける',
        TURN_OFF_BLUE_LIGHT: '青いライトを消す',
        TURN_ON_LED_MATRIX: 'LEDマトリックスをつける',
        TURN_OFF_LED_MATRIX: 'LEDマトリックスを消す',
        SOMEONE_IS_APPROACHING: '誰かが近づいている',
        PERSON_IS_MOVING_AWAY: '人が離れている',
        ITS_RAINING: '雨が降っている',
        STOP_RAIN: '雨が止んだ',
        MOVE_FORWARD: '前進',
        MOVE_BACKWARD: '後退',
        TURN_LEFT: '左に曲がる',
        TURN_RIGHT: '右に曲がる',
        FOLLOW_TRACK: '軌跡を追う',
        FOLLOW_PERSON: '人を追う',
        AVOID_OBSTACLE: '障害物を避ける',
        SEEK_LIGHT: '光を求める',
        STOP: '止まる',
        START_FEEDING: '餌やりを開始',
        STOP_FEEDING: '餌やりを止める',
        TURN_ON_COLORFUL_LIGHT: 'カラフルライトをつける',
        TURN_OFF_COLORFUL_LIGHT: 'カラフルライトを消す',
        TURN_ON_BUZZER: 'ブザーをつける',
        TURN_OFF_BUZZER: 'ブザーを消す',
        INCREASE_VOLUME: '音量を上げる',
        DECREASE_VOLUME: '音量を下げる',
        MAXIMUM_VOLUME: '最大音量',
        MEDIUM_VOLUME: '中間音量',
        MINIMUM_VOLUME: '最小音量',
        INCREASE_SERVO_ANGLE: 'サーボ角度を増やす',
        DECREASE_SERVO_ANGLE: 'サーボ角度を減らす',
        CURRENT_TEMPERATURE: '現在の温度は？',
        CURRENT_HUMIDITY: '現在の湿度は？',
        CURRENT_RAINFALL_AMOUNT: '現在の降雨量は？',
        CURRENT_LIGHT_INTENSITY: '現在の光強度は？',
        CURRENT_SOIL_MOISTURE: '現在の土壌湿度は？',
        CURRENT_WATER_LEVEL: '現在の水位は？',
        WHAT_TIME_IS_IT: '今何時？',
        CURRENT_DISTANCE: '現在の距離は？',
        TURN_ON: '電源オン',
        TURN_OFF: '電源オフ',
        OPEN_WINDOW: '窓を開ける',
        CLOSE_WINDOW: '窓を閉める',
        OPEN_DOOR: 'ドアを開ける',
        CLOSE_DOOR: 'ドアを閉める',
        FLAG_UP: '国旗を掲げる',
        FLAG_DOWN: '国旗を降ろす',
        CURTAIN_ON: 'カーテンを開ける',
        CURTAIN_OFF: 'カーテンを閉める',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: '現在の総揮発性有機化合物濃度はどのくらいですか?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: '現在の二酸化炭素濃度はどのくらいですか?',
        CURRENT_AIR_QUALITY_INDEX: '現在の大気品質指数はどのくらいですか?',

        Approach_Alar: '誰かが近づいたら警報を鳴らしてください',
        CURRENT_TEMPERATURE_IS: '現在の温度は',
        DEGREES: '度',
        CURRENT_RAINFALL_PERCENTAGE: '現在の降雨量はパーセント',
        CURRENT_HUMIDITY_PERCENTAGE: '現在の湿度はパーセント',
        CURRENT_LIGHT_INTENSITY_IS: '現在の光強度は',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: '現在の土壌湿度はパーセント',
        CURRENT_WATER_LEVEL_IS: '現在の水位は',
        CURRENT_BEIJING_TIME: '現在の北京時間は',
        CURRENT_DISTANCE_IS: '現在の距離は',
        POINT: 'ポイント',
        MINUTE: '分',
        SECOND: '秒',
        ROUND_HOUR: 'ちょうど',
        MILLILITERS: 'ミリリットル',
        MILLIMETERS: 'ミリメートル',
        CENTIMETERS: 'センチメートル',
        METERS: 'メートル',
        KILOMETERS: 'キロメートル',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: '現在の総揮発性有機化合物濃度は十億分の1です',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: '現在の二酸化炭素濃度は百万分の1です',
        CURRENT_AIR_QUALITY_INDEX_IS: '現在の大気品質指数は X です',
    });
Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        SPEECH_RECOGNITION: '음성 인식',
        YUNYININIT: '음성 인식 모듈 %1 RX %2 TX %3 초기화',
        YUNYINSHIBIE: '%1 명령 인식',
        YUNYINQINGCHU: '인식 결과 지우기',
        BOXIAOSHU: '%1 소수 방송',
        BOZHENGSHU: '%1 정수 방송',
        YUYINBOBAO: '%1 방송',
        SOFT_SERIAL: '소프트 시리얼',
        HARD_SERIAL: '하드 시리얼',
        TURN_ON_LIGHT: '불을 켜다',
        TURN_OFF_LIGHT: '불을 끄다',
        INCREASE_BRIGHTNESS: '밝기를 높이다',
        DECREASE_BRIGHTNESS: '밝기를 낮추다',
        TURN_ON_FAN: '선풍기를 켜다',
        TURN_OFF_FAN: '선풍기를 끄다',
        INCREASE_WIND_SPEED: '풍속을 높이다',
        DECREASE_WIND_SPEED: '풍속을 낮추다',
        WATER_PLANTS: '식물에 물 주기',
        STOP_WATERING: '물 주기 중지',
        PLAY_MUSIC: '음악 재생',
        STOP_MUSIC: '음악 중지',
        TURN_ON_RED_LIGHT: '빨간 불을 켜다',
        TURN_OFF_RED_LIGHT: '빨간 불을 끄다',
        TURN_ON_GREEN_LIGHT: '녹색 불을 켜다',
        TURN_OFF_GREEN_LIGHT: '녹색 불을 끄다',
        TURN_ON_BLUE_LIGHT: '파란 불을 켜다',
        TURN_OFF_BLUE_LIGHT: '파란 불을 끄다',
        TURN_ON_LED_MATRIX: 'LED 매트릭스를 켜다',
        TURN_OFF_LED_MATRIX: 'LED 매트릭스를 끄다',
        SOMEONE_IS_APPROACHING: '누군가 다가오고 있다',
        PERSON_IS_MOVING_AWAY: '사람이 멀어지고 있다',
        ITS_RAINING: '비가 오고 있다',
        STOP_RAIN: '비가 멈췄다',
        MOVE_FORWARD: '앞으로 이동',
        MOVE_BACKWARD: '뒤로 이동',
        TURN_LEFT: '왼쪽으로 돌다',
        TURN_RIGHT: '오른쪽으로 돌다',
        FOLLOW_TRACK: '트랙 추적',
        FOLLOW_PERSON: '사람 따르기',
        AVOID_OBSTACLE: '장애물 피하기',
        SEEK_LIGHT: '빛 추구',
        STOP: '멈추다',
        START_FEEDING: '먹이 주기 시작',
        STOP_FEEDING: '먹이 주기 중지',
        TURN_ON_COLORFUL_LIGHT: '컬러풀 라이트 켜기',
        TURN_OFF_COLORFUL_LIGHT: '컬러풀 라이트 끄기',
        TURN_ON_BUZZER: '부저 켜기',
        TURN_OFF_BUZZER: '부저 끄기',
        INCREASE_VOLUME: '볼륨 높이기',
        DECREASE_VOLUME: '볼륨 낮추기',
        MAXIMUM_VOLUME: '최대 볼륨',
        MEDIUM_VOLUME: '중간 볼륨',
        MINIMUM_VOLUME: '최소 볼륨',
        INCREASE_SERVO_ANGLE: '서보 각도 증가',
        DECREASE_SERVO_ANGLE: '서보 각도 감소',
        CURRENT_TEMPERATURE: '현재 온도는?',
        CURRENT_HUMIDITY: '현재 습도는?',
        CURRENT_RAINFALL_AMOUNT: '현재 강우량은?',
        CURRENT_LIGHT_INTENSITY: '현재 빛 강도는?',
        CURRENT_SOIL_MOISTURE: '현재 토양 습도는?',
        CURRENT_WATER_LEVEL: '현재 수위는?',
        WHAT_TIME_IS_IT: '지금 몇 시야?',
        CURRENT_DISTANCE: '현재 거리는?',
        TURN_ON: '켜기',
        TURN_OFF: '끄기',
        OPEN_WINDOW: '창문을 열다',
        CLOSE_WINDOW: '창문을 닫다',
        OPEN_DOOR: '문을 열다',
        CLOSE_DOOR: '문을 닫다',
        FLAG_UP: '국기를 올리다',
        FLAG_DOWN: '국기를 내리다',
        CURTAIN_ON: '커튼을 열다',
        CURTAIN_OFF: '커튼을 닫다',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: '현재 총휘발성유기화합물 농도는 얼마입니까?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: '현재 이산화탄소 농도는 얼마입니까?',
        CURRENT_AIR_QUALITY_INDEX: '현재 대기질 지수는 얼마입니까?',

        Approach_Alar: '누군가 접근하면 경보를 울려주세요',
        CURRENT_TEMPERATURE_IS: '현재 온도는',
        DEGREES: '도',
        CURRENT_RAINFALL_PERCENTAGE: '현재 강우량은 퍼센트',
        CURRENT_HUMIDITY_PERCENTAGE: '현재 습도는 퍼센트',
        CURRENT_LIGHT_INTENSITY_IS: '현재 빛 강도는',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: '현재 토양 습도는 퍼센트',
        CURRENT_WATER_LEVEL_IS: '현재 수위는',
        CURRENT_BEIJING_TIME: '현재 베이징 시간은',
        CURRENT_DISTANCE_IS: '현재 거리는',
        POINT: '포인트',
        MINUTE: '분',
        SECOND: '초',
        ROUND_HOUR: '정각',
        MILLILITERS: '밀리리터',
        MILLIMETERS: '밀리미터',
        CENTIMETERS: '센티미터',
        METERS: '미터',
        KILOMETERS: '킬로미터',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: '현재 총휘발성유기화합물 농도는 십억분의 1입니다',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: '현재 이산화탄소 농도는 백만분의 1입니다',
        CURRENT_AIR_QUALITY_INDEX_IS: '현재 대기질 지수는 입니다',
    });
Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        SPEECH_RECOGNITION: 'Rozpoznawanie mowy',
        YUNYININIT: 'Inicjalizuj moduł rozpoznawania mowy %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Rozpoznano polecenie %1',
        YUNYINQINGCHU: 'Wyczyść wyniki rozpoznawania',
        BOXIAOSHU: 'Ogłoś liczbę dziesiętną %1',
        BOZHENGSHU: 'Ogłoś liczbę całkowitą %1',
        YUYINBOBAO: 'Ogłoś %1',
        SOFT_SERIAL: 'Miękki port szeregowy',
        HARD_SERIAL: 'Twardy port szeregowy',
        TURN_ON_LIGHT: 'Włącz światło',
        TURN_OFF_LIGHT: 'Wyłącz światło',
        INCREASE_BRIGHTNESS: 'Zwiększ jasność',
        DECREASE_BRIGHTNESS: 'Zmniejsz jasność',
        TURN_ON_FAN: 'Włącz wentylator',
        TURN_OFF_FAN: 'Wyłącz wentylator',
        INCREASE_WIND_SPEED: 'Zwiększ prędkość wiatru',
        DECREASE_WIND_SPEED: 'Zmniejsz prędkość wiatru',
        WATER_PLANTS: 'Podlej rośliny',
        STOP_WATERING: 'Zatrzymaj podlewanie',
        PLAY_MUSIC: 'Odtwórz muzykę',
        STOP_MUSIC: 'Zatrzymaj muzykę',
        TURN_ON_RED_LIGHT: 'Włącz czerwone światło',
        TURN_OFF_RED_LIGHT: 'Wyłącz czerwone światło',
        TURN_ON_GREEN_LIGHT: 'Włącz zielone światło',
        TURN_OFF_GREEN_LIGHT: 'Wyłącz zielone światło',
        TURN_ON_BLUE_LIGHT: 'Włącz niebieskie światło',
        TURN_OFF_BLUE_LIGHT: 'Wyłącz niebieskie światło',
        TURN_ON_LED_MATRIX: 'Włącz matrycę LED',
        TURN_OFF_LED_MATRIX: 'Wyłącz matrycę LED',
        SOMEONE_IS_APPROACHING: 'Ktoś się zbliża',
        PERSON_IS_MOVING_AWAY: 'Osoba się oddala',
        ITS_RAINING: 'Pada deszcz',
        STOP_RAIN: 'Deszcz ustał',
        MOVE_FORWARD: 'Poruszaj się do przodu',
        MOVE_BACKWARD: 'Poruszaj się do tyłu',
        TURN_LEFT: 'Skręć w lewo',
        TURN_RIGHT: 'Skręć w prawo',
        FOLLOW_TRACK: 'Śledzenie toru',
        FOLLOW_PERSON: 'Śledzenie osoby',
        AVOID_OBSTACLE: 'Unikanie przeszkód',
        SEEK_LIGHT: 'Szukanie światła',
        STOP: 'Zatrzymaj',
        START_FEEDING: 'Rozpocznij karmienie',
        STOP_FEEDING: 'Zatrzymaj karmienie',
        TURN_ON_COLORFUL_LIGHT: 'Włącz kolorowe światło',
        TURN_OFF_COLORFUL_LIGHT: 'Wyłącz kolorowe światło',
        TURN_ON_BUZZER: 'Włącz brzęczyk',
        TURN_OFF_BUZZER: 'Wyłącz brzęczyk',
        INCREASE_VOLUME: 'Zwiększ głośność',
        DECREASE_VOLUME: 'Zmniejsz głośność',
        MAXIMUM_VOLUME: 'Maksymalna głośność',
        MEDIUM_VOLUME: 'Średnia głośność',
        MINIMUM_VOLUME: 'Minimalna głośność',
        INCREASE_SERVO_ANGLE: 'Zwiększ kąt serwa',
        DECREASE_SERVO_ANGLE: 'Zmniejsz kąt serwa',
        CURRENT_TEMPERATURE: 'Jaka jest aktualna temperatura?',
        CURRENT_HUMIDITY: 'Jaka jest aktualna wilgotność?',
        CURRENT_RAINFALL_AMOUNT: 'Jaka jest aktualna ilość opadów?',
        CURRENT_LIGHT_INTENSITY: 'Jaka jest aktualna intensywność światła?',
        CURRENT_SOIL_MOISTURE: 'Jaka jest aktualna wilgotność gleby?',
        CURRENT_WATER_LEVEL: 'Jaki jest aktualny poziom wody?',
        WHAT_TIME_IS_IT: 'Która godzina?',
        CURRENT_DISTANCE: 'Jaka jest aktualna odległość?',
        TURN_ON: 'Włącz',
        TURN_OFF: 'Wyłącz',
        OPEN_WINDOW: 'Otwórz okno',
        CLOSE_WINDOW: 'Zamknij okno',
        OPEN_DOOR: 'Otwórz drzwi',
        CLOSE_DOOR: 'Zamknij drzwi',
        FLAG_UP: 'Podnieść flagę',
        FLAG_DOWN: 'Opuścić flagę',
        CURTAIN_ON: 'Otworzyć zasłonę',
        CURTAIN_OFF: 'Zamknąć zasłonę',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'Jakie jest obecne stężenie całkowitych lotnych związków organicznych?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'Jakie jest obecne stężenie dwutlenku węgla?',
        CURRENT_AIR_QUALITY_INDEX: 'Jaki jest obecny wskaźnik jakości powietrza?',

        Approach_Alar: 'Jeśli ktoś się zbliża, proszę uruchomić alarm',
        CURRENT_TEMPERATURE_IS: 'Aktualna temperatura to',
        DEGREES: 'stopnie',
        CURRENT_RAINFALL_PERCENTAGE: 'Aktualna ilość opadów to procent',
        CURRENT_HUMIDITY_PERCENTAGE: 'Aktualna wilgotność to procent',
        CURRENT_LIGHT_INTENSITY_IS: 'Aktualna intensywność światła to',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'Aktualna wilgotność gleby to procent',
        CURRENT_WATER_LEVEL_IS: 'Aktualny poziom wody to',
        CURRENT_BEIJING_TIME: 'Aktualny czas w Pekinie to',
        CURRENT_DISTANCE_IS: 'Aktualna odległość to',
        POINT: 'punkt',
        MINUTE: 'minuta',
        SECOND: 'sekunda',
        ROUND_HOUR: 'dokładnie',
        MILLILITERS: 'mililitry',
        MILLIMETERS: 'milimetry',
        CENTIMETERS: 'centymetry',
        METERS: 'metry',
        KILOMETERS: 'kilometry',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'Obecne stężenie całkowitych lotnych związków organicznych wynosi części na miliard',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'Obecne stężenie dwutlenku węgla wynosi X części na milion',
        CURRENT_AIR_QUALITY_INDEX_IS: 'Obecny wskaźnik jakości powietrza wynosi',
    });
Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        SPEECH_RECOGNITION: 'Reconhecimento de Fala',
        YUNYININIT: 'Inicializar o módulo de reconhecimento de fala %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Comando %1 reconhecido',
        YUNYINQINGCHU: 'Limpar resultados de reconhecimento',
        BOXIAOSHU: 'Anunciar decimal %1',
        BOZHENGSHU: 'Anunciar número inteiro %1',
        YUYINBOBAO: 'Anunciar %1',
        SOFT_SERIAL: 'Serial suave',
        HARD_SERIAL: 'Serial rígido',
        TURN_ON_LIGHT: 'Ligar a luz',
        TURN_OFF_LIGHT: 'Desligar a luz',
        INCREASE_BRIGHTNESS: 'Aumentar o brilho',
        DECREASE_BRIGHTNESS: 'Diminuir o brilho',
        TURN_ON_FAN: 'Ligar o ventilador',
        TURN_OFF_FAN: 'Desligar o ventilador',
        INCREASE_WIND_SPEED: 'Aumentar a velocidade do vento',
        DECREASE_WIND_SPEED: 'Diminuir a velocidade do vento',
        WATER_PLANTS: 'Regar as plantas',
        STOP_WATERING: 'Parar de regar',
        PLAY_MUSIC: 'Tocar música',
        STOP_MUSIC: 'Parar música',
        TURN_ON_RED_LIGHT: 'Ligar a luz vermelha',
        TURN_OFF_RED_LIGHT: 'Desligar a luz vermelha',
        TURN_ON_GREEN_LIGHT: 'Ligar a luz verde',
        TURN_OFF_GREEN_LIGHT: 'Desligar a luz verde',
        TURN_ON_BLUE_LIGHT: 'Ligar a luz azul',
        TURN_OFF_BLUE_LIGHT: 'Desligar a luz azul',
        TURN_ON_LED_MATRIX: 'Ligar a matriz LED',
        TURN_OFF_LED_MATRIX: 'Desligar a matriz LED',
        SOMEONE_IS_APPROACHING: 'Alguém está se aproximando',
        PERSON_IS_MOVING_AWAY: 'A pessoa está se afastando',
        ITS_RAINING: 'Está chovendo',
        STOP_RAIN: 'A chuva parou',
        MOVE_FORWARD: 'Mover para frente',
        MOVE_BACKWARD: 'Mover para trás',
        TURN_LEFT: 'Virar à esquerda',
        TURN_RIGHT: 'Virar à direita',
        FOLLOW_TRACK: 'Seguir trilha',
        FOLLOW_PERSON: 'Seguir pessoa',
        AVOID_OBSTACLE: 'Evitar obstáculos',
        SEEK_LIGHT: 'Buscar luz',
        STOP: 'Parar',
        START_FEEDING: 'Começar a alimentar',
        STOP_FEEDING: 'Parar de alimentar',
        TURN_ON_COLORFUL_LIGHT: 'Ligar a luz colorida',
        TURN_OFF_COLORFUL_LIGHT: 'Desligar a luz colorida',
        TURN_ON_BUZZER: 'Ligar o buzzer',
        TURN_OFF_BUZZER: 'Desligar o buzzer',
        INCREASE_VOLUME: 'Aumentar o volume',
        DECREASE_VOLUME: 'Diminuir o volume',
        MAXIMUM_VOLUME: 'Volume máximo',
        MEDIUM_VOLUME: 'Volume médio',
        MINIMUM_VOLUME: 'Volume mínimo',
        INCREASE_SERVO_ANGLE: 'Aumentar o ângulo do servo',
        DECREASE_SERVO_ANGLE: 'Diminuir o ângulo do servo',
        CURRENT_TEMPERATURE: 'Qual é a temperatura atual?',
        CURRENT_HUMIDITY: 'Qual é a umidade atual?',
        CURRENT_RAINFALL_AMOUNT: 'Qual é a quantidade de chuva atual?',
        CURRENT_LIGHT_INTENSITY: 'Qual é a intensidade de luz atual?',
        CURRENT_SOIL_MOISTURE: 'Qual é a umidade do solo atual?',
        CURRENT_WATER_LEVEL: 'Qual é o nível de água atual?',
        WHAT_TIME_IS_IT: 'Que horas são?',
        CURRENT_DISTANCE: 'Qual é a distância atual?',
        TURN_ON: 'Ligar',
        TURN_OFF: 'Desligar',
        OPEN_WINDOW: 'Abrir a janela',
        CLOSE_WINDOW: 'Fechar a janela',
        OPEN_DOOR: 'Abrir a porta',
        CLOSE_DOOR: 'Fechar a porta',
        FLAG_UP: 'Hastear a bandeira',
        FLAG_DOWN: 'Arriar a bandeira',
        CURTAIN_ON: 'Abrir a cortina',
        CURTAIN_OFF: 'Fechar a cortina',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'Qual é a concentração atual de compostos orgânicos voláteis totais?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'Qual é a concentração atual de dióxido de carbono?',
        CURRENT_AIR_QUALITY_INDEX: 'Qual é o índice atual de qualidade do ar?',

        Approach_Alar: 'Se alguém se aproximar, por favor acione o alarme',
        CURRENT_TEMPERATURE_IS: 'A temperatura atual é',
        DEGREES: 'graus',
        CURRENT_RAINFALL_PERCENTAGE: 'A quantidade de chuva atual é de porcentagem',
        CURRENT_HUMIDITY_PERCENTAGE: 'A umidade atual é de porcentagem',
        CURRENT_LIGHT_INTENSITY_IS: 'A intensidade de luz atual é',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'A umidade do solo atual é de porcentagem',
        CURRENT_WATER_LEVEL_IS: 'O nível de água atual é',
        CURRENT_BEIJING_TIME: 'A hora atual em Pequim é',
        CURRENT_DISTANCE_IS: 'A distância atual é',
        POINT: 'ponto',
        MINUTE: 'minuto',
        SECOND: 'segundo',
        ROUND_HOUR: 'em ponto',
        MILLILITERS: 'mililitros',
        MILLIMETERS: 'milímetros',
        CENTIMETERS: 'centímetros',
        METERS: 'metros',
        KILOMETERS: 'quilômetros',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'A concentração atual de compostos orgânicos voláteis totais é de partes por bilhão',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'A concentração atual de dióxido de carbono é de partes por milhão',
        CURRENT_AIR_QUALITY_INDEX_IS: 'O índice atual de qualidade do ar é',
    });
Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        SPEECH_RECOGNITION: 'Распознавание речи',
        YUNYININIT: 'Инициализация модуля распознавания речи %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Команда %1 распознана',
        YUNYINQINGCHU: 'Очистить результаты распознавания',
        BOXIAOSHU: 'Объявить десятичное число %1',
        BOZHENGSHU: 'Объявить целое число %1',
        YUYINBOBAO: 'Объявить %1',
        SOFT_SERIAL: 'Софт-сериал',
        HARD_SERIAL: 'Аппаратный сериал',
        TURN_ON_LIGHT: 'Включить свет',
        TURN_OFF_LIGHT: 'Выключить свет',
        INCREASE_BRIGHTNESS: 'Увеличить яркость',
        DECREASE_BRIGHTNESS: 'Уменьшить яркость',
        TURN_ON_FAN: 'Включить вентилятор',
        TURN_OFF_FAN: 'Выключить вентилятор',
        INCREASE_WIND_SPEED: 'Увеличить скорость ветра',
        DECREASE_WIND_SPEED: 'Уменьшить скорость ветра',
        WATER_PLANTS: 'Полить растения',
        STOP_WATERING: 'Остановить полив',
        PLAY_MUSIC: 'Воспроизвести музыку',
        STOP_MUSIC: 'Остановить музыку',
        TURN_ON_RED_LIGHT: 'Включить красный свет',
        TURN_OFF_RED_LIGHT: 'Выключить красный свет',
        TURN_ON_GREEN_LIGHT: 'Включить зелёный свет',
        TURN_OFF_GREEN_LIGHT: 'Выключить зелёный свет',
        TURN_ON_BLUE_LIGHT: 'Включить синий свет',
        TURN_OFF_BLUE_LIGHT: 'Выключить синий свет',
        TURN_ON_LED_MATRIX: 'Включить LED-матрицу',
        TURN_OFF_LED_MATRIX: 'Выключить LED-матрицу',
        SOMEONE_IS_APPROACHING: 'Кто-то приближается',
        PERSON_IS_MOVING_AWAY: 'Человек удаляется',
        ITS_RAINING: 'Идёт дождь',
        STOP_RAIN: 'Дождь прекратился',
        MOVE_FORWARD: 'Двигаться вперёд',
        MOVE_BACKWARD: 'Двигаться назад',
        TURN_LEFT: 'Повернуть налево',
        TURN_RIGHT: 'Повернуть направо',
        FOLLOW_TRACK: 'Следовать по трассе',
        FOLLOW_PERSON: 'Следовать за человеком',
        AVOID_OBSTACLE: 'Избегать препятствий',
        SEEK_LIGHT: 'Искать свет',
        STOP: 'Остановить',
        START_FEEDING: 'Начать кормление',
        STOP_FEEDING: 'Остановить кормление',
        TURN_ON_COLORFUL_LIGHT: 'Включить разноцветный свет',
        TURN_OFF_COLORFUL_LIGHT: 'Выключить разноцветный свет',
        TURN_ON_BUZZER: 'Включить зуммер',
        TURN_OFF_BUZZER: 'Выключить зуммер',
        INCREASE_VOLUME: 'Увеличить громкость',
        DECREASE_VOLUME: 'Уменьшить громкость',
        MAXIMUM_VOLUME: 'Максимальная громкость',
        MEDIUM_VOLUME: 'Средняя громкость',
        MINIMUM_VOLUME: 'Минимальная громкость',
        INCREASE_SERVO_ANGLE: 'Увеличить угол сервопривода',
        DECREASE_SERVO_ANGLE: 'Уменьшить угол сервопривода',
        CURRENT_TEMPERATURE: 'Какова текущая температура?',
        CURRENT_HUMIDITY: 'Какова текущая влажность?',
        CURRENT_RAINFALL_AMOUNT: 'Каково текущее количество осадков?',
        CURRENT_LIGHT_INTENSITY: 'Какова текущая интенсивность света?',
        CURRENT_SOIL_MOISTURE: 'Какова текущая влажность почвы?',
        CURRENT_WATER_LEVEL: 'Каков текущий уровень воды?',
        WHAT_TIME_IS_IT: 'Сколько времени?',
        CURRENT_DISTANCE: 'Каково текущее расстояние?',
        TURN_ON: 'Включить',
        TURN_OFF: 'Выключить',
        OPEN_WINDOW: 'Открыть окно',
        CLOSE_WINDOW: 'Закрыть окно',
        OPEN_DOOR: 'Открыть дверь',
        CLOSE_DOOR: 'Закрыть дверь',
        FLAG_UP: 'Nодъём флага',
        FLAG_DOWN: 'Cпуск флага',
        CURTAIN_ON: 'Oткрыть штору',
        CURTAIN_OFF: 'Закрой штору',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'Какова текущая концентрация летучих органических соединений?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'Какова текущая концентрация углекислого газа?',
        CURRENT_AIR_QUALITY_INDEX: 'Каков текущий индекс качества воздуха?',

        Approach_Alar: 'Если кто-то приближается, пожалуйста, включите сигнализацию',
        CURRENT_TEMPERATURE_IS: 'Текущая температура составляет',
        DEGREES: 'градусов',
        CURRENT_RAINFALL_PERCENTAGE: 'Текущее количество осадков составляет процентов',
        CURRENT_HUMIDITY_PERCENTAGE: 'Текущая влажность составляет процентов',
        CURRENT_LIGHT_INTENSITY_IS: 'Текущая интенсивность света составляет',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'Текущая влажность почвы составляет процентов',
        CURRENT_WATER_LEVEL_IS: 'Текущий уровень воды составляет',
        CURRENT_BEIJING_TIME: 'Текущее время в Пекине составляет',
        CURRENT_DISTANCE_IS: 'Текущее расстояние составляет',
        POINT: 'точка',
        MINUTE: 'минута',
        SECOND: 'секунда',
        ROUND_HOUR: 'ровно',
        MILLILITERS: 'миллилитров',
        MILLIMETERS: 'миллиметров',
        CENTIMETERS: 'сантиметров',
        METERS: 'метров',
        KILOMETERS: 'километров',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'Текущая концентрация летучих органических соединений (ЛОС) составляет частей на миллиард',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'Текущая концентрация углекислого газа составляет частей на миллион',
        CURRENT_AIR_QUALITY_INDEX_IS: 'Текущий индекс качества воздуха составляет',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        SPEECH_RECOGNITION: '語音識別',
        YUNYININIT: '初始化語音識別模組 %1 RX %2 TX %3',
        YUNYINSHIBIE: '識別到 %1 指令',
        YUNYINQINGCHU: '清除識別結果',
        BOXIAOSHU: '播報小數 %1',
        BOZHENGSHU: '播報整數 %1',
        YUYINBOBAO: '播報 %1',
        SOFT_SERIAL: '軟串口',
        HARD_SERIAL: '硬串口',
        TURN_ON_LIGHT: '開燈',
        TURN_OFF_LIGHT: '關燈',
        INCREASE_BRIGHTNESS: '調亮一點',
        DECREASE_BRIGHTNESS: '調暗一點',
        TURN_ON_FAN: '開風扇',
        TURN_OFF_FAN: '關風扇',
        INCREASE_WIND_SPEED: '風大一點',
        DECREASE_WIND_SPEED: '風小一點',
        WATER_PLANTS: '澆水',
        STOP_WATERING: '停止澆水',
        PLAY_MUSIC: '播放音樂',
        STOP_MUSIC: '關閉音樂',
        TURN_ON_RED_LIGHT: '打開紅燈',
        TURN_OFF_RED_LIGHT: '關閉紅燈',
        TURN_ON_GREEN_LIGHT: '打開綠燈',
        TURN_OFF_GREEN_LIGHT: '關閉綠燈',
        TURN_ON_BLUE_LIGHT: '打開藍燈',
        TURN_OFF_BLUE_LIGHT: '關閉藍燈',
        TURN_ON_LED_MATRIX: '打開點陣',
        TURN_OFF_LED_MATRIX: '關閉點陣',
        SOMEONE_IS_APPROACHING: '有人靠近',
        PERSON_IS_MOVING_AWAY: '人遠離',
        ITS_RAINING: '下雨',
        STOP_RAIN: '停雨',
        MOVE_FORWARD: '前進',
        MOVE_BACKWARD: '後退',
        TURN_LEFT: '左轉',
        TURN_RIGHT: '右轉',
        FOLLOW_TRACK: '循跡',
        FOLLOW_PERSON: '跟隨',
        AVOID_OBSTACLE: '避障',
        SEEK_LIGHT: '尋光',
        STOP: '停止',
        START_FEEDING: '開始餵食',
        STOP_FEEDING: '停止餵食',
        TURN_ON_COLORFUL_LIGHT: '打開彩燈',
        TURN_OFF_COLORFUL_LIGHT: '關閉彩燈',
        TURN_ON_BUZZER: '打開蜂鳴器',
        TURN_OFF_BUZZER: '關閉蜂鳴器',
        INCREASE_VOLUME: '增大音量',
        DECREASE_VOLUME: '減小音量',
        MAXIMUM_VOLUME: '最大音量',
        MEDIUM_VOLUME: '中等音量',
        MINIMUM_VOLUME: '最小音量',
        INCREASE_SERVO_ANGLE: '舵機角度增大',
        DECREASE_SERVO_ANGLE: '舵機角度減少',
        CURRENT_TEMPERATURE: '當前溫度是多少',
        CURRENT_HUMIDITY: '當前濕度是多少',
        CURRENT_RAINFALL_AMOUNT: '當前雨水量是多少',
        CURRENT_LIGHT_INTENSITY: '當前光照強度是多少',
        CURRENT_SOIL_MOISTURE: '當前土壤濕度是多少',
        CURRENT_WATER_LEVEL: '當前水位是多少',
        WHAT_TIME_IS_IT: '幾點了',
        CURRENT_DISTANCE: '現在距離是多少',
        TURN_ON: '開機',
        TURN_OFF: '關機',
        OPEN_WINDOW: '打開窗户',
        CLOSE_WINDOW: '關閉窗户',
        OPEN_DOOR: '打開門',
        CLOSE_DOOR: '關閉門',
        FLAG_UP: '升旗',
        FLAG_DOWN: '降旗',
        CURTAIN_ON: '拉開窗簾',
        CURTAIN_OFF: '關閉窗簾',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: '當前總揮發性有機物濃度是多少',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: '當前二氧化碳濃度是多少',
        CURRENT_AIR_QUALITY_INDEX: '當前空氣質量指數是多少',

        Approach_Alar: '有人靠近請發出警報',
        CURRENT_TEMPERATURE_IS: '當前溫度為',
        DEGREES: '度',
        CURRENT_RAINFALL_PERCENTAGE: '當前雨水量為百分之',
        CURRENT_HUMIDITY_PERCENTAGE: '當前濕度為百分之',
        CURRENT_LIGHT_INTENSITY_IS: '當前光照強度為',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: '當前土壤濕度為百分之',
        CURRENT_WATER_LEVEL_IS: '當前水位為',
        CURRENT_BEIJING_TIME: '現在是北京時間',
        CURRENT_DISTANCE_IS: '當前距離為',
        POINT: '點',
        MINUTE: '分',
        SECOND: '秒',
        ROUND_HOUR: '點整',
        MILLILITERS: '毫升',
        MILLIMETERS: '毫米',
        CENTIMETERS: '厘米',
        METERS: '米',
        KILOMETERS: '千米',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: '當前總揮發性有機物濃度為十億分之',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: '當前二氧化碳濃度為百萬分之',
        CURRENT_AIR_QUALITY_INDEX_IS: '當前空氣質量指數為',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        SPEECH_RECOGNITION: '语音识别',
        YUNYININIT: '初始化语音识别模块 %1 RX %2 TX %3',
        YUNYINSHIBIE: '识别到 %1 指令',
        YUNYINQINGCHU: '清除识别结果',
        BOXIAOSHU: '播报小数 %1',
        BOZHENGSHU: '播报整数 %1',
        YUYINBOBAO: '播报 %1',
        SOFT_SERIAL: '软串口',
        HARD_SERIAL: '硬串口',
        TURN_ON_LIGHT: '开灯',
        TURN_OFF_LIGHT: '关灯',
        INCREASE_BRIGHTNESS: '调亮一点',
        DECREASE_BRIGHTNESS: '调暗一点',
        TURN_ON_FAN: '开风扇',
        TURN_OFF_FAN: '关风扇',
        INCREASE_WIND_SPEED: '风大一点',
        DECREASE_WIND_SPEED: '风小一点',
        WATER_PLANTS: '浇水',
        STOP_WATERING: '停止浇水',
        PLAY_MUSIC: '播放音乐',
        STOP_MUSIC: '关闭音乐',
        TURN_ON_RED_LIGHT: '打开红灯',
        TURN_OFF_RED_LIGHT: '关闭红灯',
        TURN_ON_GREEN_LIGHT: '打开绿灯',
        TURN_OFF_GREEN_LIGHT: '关闭绿灯',
        TURN_ON_BLUE_LIGHT: '打开蓝灯',
        TURN_OFF_BLUE_LIGHT: '关闭蓝灯',
        TURN_ON_LED_MATRIX: '打开点阵',
        TURN_OFF_LED_MATRIX: '关闭点阵',
        SOMEONE_IS_APPROACHING: '有人靠近',
        PERSON_IS_MOVING_AWAY: '人远离',
        ITS_RAINING: '下雨',
        STOP_RAIN: '停雨',
        MOVE_FORWARD: '前进',
        MOVE_BACKWARD: '后退',
        TURN_LEFT: '左转',
        TURN_RIGHT: '右转',
        FOLLOW_TRACK: '循迹',
        FOLLOW_PERSON: '跟随',
        AVOID_OBSTACLE: '避障',
        SEEK_LIGHT: '寻光',
        STOP: '停止',
        START_FEEDING: '开始喂食',
        STOP_FEEDING: '停止喂食',
        TURN_ON_COLORFUL_LIGHT: '打开彩灯',
        TURN_OFF_COLORFUL_LIGHT: '关闭彩灯',
        TURN_ON_BUZZER: '打开蜂鸣器',
        TURN_OFF_BUZZER: '关闭蜂鸣器',
        INCREASE_VOLUME: '增大音量',
        DECREASE_VOLUME: '减小音量',
        MAXIMUM_VOLUME: '最大音量',
        MEDIUM_VOLUME: '中等音量',
        MINIMUM_VOLUME: '最小音量',
        INCREASE_SERVO_ANGLE: '舵机角度增大',
        DECREASE_SERVO_ANGLE: '舵机角度减少',
        CURRENT_TEMPERATURE: '当前温度是多少',
        CURRENT_HUMIDITY: '当前湿度是多少',
        CURRENT_RAINFALL_AMOUNT: '当前雨水量是多少',
        CURRENT_LIGHT_INTENSITY: '当前光照强度是多少',
        CURRENT_SOIL_MOISTURE: '当前土壤湿度是多少',
        CURRENT_WATER_LEVEL: '当前水位是多少',
        WHAT_TIME_IS_IT: '几点了',
        CURRENT_DISTANCE: '现在距离是多少',
        TURN_ON: '开机',
        TURN_OFF: '关机',
        OPEN_WINDOW: '打开窗户',
        CLOSE_WINDOW: '关闭窗户',
        OPEN_DOOR: '打开门',
        CLOSE_DOOR: '关闭门',
        FLAG_UP: '升旗',
        FLAG_DOWN: '降旗',
        CURTAIN_ON: '拉开窗帘',
        CURTAIN_OFF: '关闭窗帘',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: '当前总挥发性有机物浓度是多少',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: '当前二氧化碳浓度是多少',
        CURRENT_AIR_QUALITY_INDEX: '当前空气质量指数是多少',
        Approach_Alar: '有人靠近请发出警报',

        CURRENT_TEMPERATURE_IS: '当前温度为',
        DEGREES: '度',
        CURRENT_RAINFALL_PERCENTAGE: '当前雨水量为百分之',
        CURRENT_HUMIDITY_PERCENTAGE: '当前湿度为百分之',
        CURRENT_LIGHT_INTENSITY_IS: '当前光照强度为',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: '当前土壤湿度为百分之',
        CURRENT_WATER_LEVEL_IS: '当前水位为',
        CURRENT_BEIJING_TIME: '现在是北京时间',
        CURRENT_DISTANCE_IS: '当前距离为',
        POINT: '点',
        MINUTE: '分',
        SECOND: '秒',
        ROUND_HOUR: '点整',
        MILLILITERS: '毫升',
        MILLIMETERS: '毫米',
        CENTIMETERS: '厘米',
        METERS: '米',
        KILOMETERS: '千米',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: '当前总挥发性有机物浓度为十亿分之',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: '当前二氧化碳浓度为百万分之',
        CURRENT_AIR_QUALITY_INDEX_IS: '当前空气质量指数为',

    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        SPEECH_RECOGNITION: 'Riconoscimento Vocale',
        YUNYININIT: 'Inizializzare il modulo di riconoscimento vocale %1 RX %2 TX %3',
        YUNYINSHIBIE: 'Comando %1 riconosciuto',
        YUNYINQINGCHU: 'Cancellare i risultati del riconoscimento',
        BOXIAOSHU: 'Annunciare il decimale %1',
        BOZHENGSHU: 'Annunciare il numero intero %1',
        YUYINBOBAO: 'Annunciare %1', 
        SOFT_SERIAL: 'Seriale morbido',
        HARD_SERIAL: 'Seriale rigido',
        TURN_ON_LIGHT: 'Accendi la luce',
        TURN_OFF_LIGHT: 'Spegni la luce',
        INCREASE_BRIGHTNESS: 'Aumenta la luminosità',
        DECREASE_BRIGHTNESS: 'Diminuisci la luminosità',
        TURN_ON_FAN: 'Accendi il ventilatore',
        TURN_OFF_FAN: 'Spegni il ventilatore',
        INCREASE_WIND_SPEED: 'Aumenta la velocità del vento',
        DECREASE_WIND_SPEED: 'Diminuisci la velocità del vento',
        WATER_PLANTS: 'Innaffia le piante',
        STOP_WATERING: 'Smetti di innaffiare',
        PLAY_MUSIC: 'Riproduci musica',
        STOP_MUSIC: 'Smetti la musica',
        TURN_ON_RED_LIGHT: 'Accendi la luce rossa',
        TURN_OFF_RED_LIGHT: 'Spegni la luce rossa',
        TURN_ON_GREEN_LIGHT: 'Accendi la luce verde',
        TURN_OFF_GREEN_LIGHT: 'Spegni la luce verde',
        TURN_ON_BLUE_LIGHT: 'Accendi la luce blu',
        TURN_OFF_BLUE_LIGHT: 'Spegni la luce blu',
        TURN_ON_LED_MATRIX: 'Accendi la matrice LED',
        TURN_OFF_LED_MATRIX: 'Spegni la matrice LED',
        SOMEONE_IS_APPROACHING: 'Qualcuno si sta avvicinando',
        PERSON_IS_MOVING_AWAY: 'La persona si sta allontanando',
        ITS_RAINING: 'Sta piovendo',
        STOP_RAIN: 'La pioggia è finita',
        MOVE_FORWARD: 'Muoviti in avanti',
        MOVE_BACKWARD: 'Muoviti all\'indietro',
        TURN_LEFT: 'Gira a sinistra',
        TURN_RIGHT: 'Gira a destra',
        FOLLOW_TRACK: 'Segui la traccia',
        FOLLOW_PERSON: 'Segui la persona',
        AVOID_OBSTACLE: 'Evita ostacoli',
        SEEK_LIGHT: 'Cerca la luce',
        STOP: 'Fermati',
        START_FEEDING: 'Inizia a nutrire',
        STOP_FEEDING: 'Smetti di nutrire',
        TURN_ON_COLORFUL_LIGHT: 'Accendi la luce colorata',
        TURN_OFF_COLORFUL_LIGHT: 'Spegni la luce colorata',
        TURN_ON_BUZZER: 'Accendi il buzzer',
        TURN_OFF_BUZZER: 'Spegni il buzzer',
        INCREASE_VOLUME: 'Aumenta il volume',
        DECREASE_VOLUME: 'Diminuisci il volume',
        MAXIMUM_VOLUME: 'Volume massimo',
        MEDIUM_VOLUME: 'Volume medio',
        MINIMUM_VOLUME: 'Volume minimo',
        INCREASE_SERVO_ANGLE: 'Aumenta l\'angolo del servo',
        DECREASE_SERVO_ANGLE: 'Diminuisci l\'angolo del servo',
        CURRENT_TEMPERATURE: 'Qual è la temperatura attuale?',
        CURRENT_HUMIDITY: 'Qual è l\'umidità attuale?',
        CURRENT_RAINFALL_AMOUNT: 'Qual è la quantità di pioggia attuale?',
        CURRENT_LIGHT_INTENSITY: 'Qual è l\'intensità luminosa attuale?',
        CURRENT_SOIL_MOISTURE: 'Qual è l\'umidità del suolo attuale?',
        CURRENT_WATER_LEVEL: 'Qual è il livello dell\'acqua attuale?',
        WHAT_TIME_IS_IT: 'Che ora è?',
        CURRENT_DISTANCE: 'Qual è la distanza attuale?',
        TURN_ON: 'Accendi',
        TURN_OFF: 'Spegni',
        OPEN_WINDOW: 'Apri la finestra',
        CLOSE_WINDOW: 'Chiudi la finestra',
        OPEN_DOOR: 'Apri la porta',
        CLOSE_DOOR: 'Chiudi la porta',
        FLAG_UP: 'Issare la bandiera',
        FLAG_DOWN: 'Ammainare la bandiera',
        CURTAIN_ON: 'Aprire la tenda',
        CURTAIN_OFF: 'Chiudere la tenda',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE: 'Qual è l’attuale concentrazione di composti organici volatili totali?',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE: 'Qual è l’attuale concentrazione di anidride carbonica?',
        CURRENT_AIR_QUALITY_INDEX: 'Qual è l’indice di qualità dell’aria attuale?',

        Approach_Alar: 'Se qualcuno si avvicina, si prega di attivare l\'allarme',
        CURRENT_TEMPERATURE_IS: 'La temperatura attuale è',
        DEGREES: 'gradi',
        CURRENT_RAINFALL_PERCENTAGE: 'La quantità di pioggia attuale è percento',
        CURRENT_HUMIDITY_PERCENTAGE: 'L\'umidità attuale è percento',
        CURRENT_LIGHT_INTENSITY_IS: 'L\'intensità luminosa attuale è',
        CURRENT_SOIL_MOISTURE_PERCENTAGE: 'L\'umidità del suolo attuale è percento',
        CURRENT_WATER_LEVEL_IS: 'Il livello dell\'acqua attuale è',
        CURRENT_BEIJING_TIME: 'L\'ora attuale a Pechino è',
        CURRENT_DISTANCE_IS: 'La distanza attuale è',
        POINT: 'punto',
        MINUTE: 'minuto',
        SECOND: 'secondo',
        ROUND_HOUR: 'in punto',
        MILLILITERS: 'millilitri',
        MILLIMETERS: 'millimetri',
        CENTIMETERS: 'centimetri',
        METERS: 'metri',
        KILOMETERS: 'chilometri',
        CURRENT_TOTAL_VOLATILE_ORGANIC_COMPOUND_CONCENTRATE_PARTS_PER_BILLION: 'L’attuale concentrazione di composti organici volatili totali è di parti per miliardo',
        CURRENT_CARBON_DIOXIDE_CONCENTRATE_PARTS_PER_MILLION: 'L’attuale concentrazione di anidride carbonica è di parti per milione',
        CURRENT_AIR_QUALITY_INDEX_IS: 'L’indice di qualità dell’aria attuale è di',
    });
    return Blockly;
}

exports = addMsg;
