/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Display',
        REGISTER_CATEGORY: 'Register Hardware',
        EVENT_CATEGORY: 'Event',
        STATE_CATEGORY: 'Update Device',
        AI_BOT_INIT_WIFI: 'Init AI-bot network SSID %1 PASSWORD %2',
        AI_BOT_INIT_STD: 'Init AI-bot %1 Mic BCLK %2 WS %3 DIN %4 %5 Speaker BCLK %6 WS %7 DOUT %8 %9 trigger pin %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED display show status %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED display %1 show chat message %2',
        SYSTEM: 'System',
        ASSISANT: 'Assisant',
        USER: 'User',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED display show emotion %1',
        AI_BOT_INIT_OLED: 'Initialize OLED display %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Register control device %1 properties: %2 control functions: open %3 close %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Register LED device name %1 LED count %2 property description %3 control functions open %4 close %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Register servo device name %1 servo count %2 property description %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Register analog sensor device name %1 property description %2 status %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Register ultrasonic device name %1 property description %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Register DHT11 device temperature function name %1 property description %2 humidity function name %3 property description %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Register WS2812 color light function name %1 LED count %2',
        AI_BOT_LOOP: 'When AI-bot event occurs %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'If event is activation',
        DO: 'DO %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Get activation message',
        AI_BOT_GET_ACTIVATION_CODE: 'Get activation code',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'If event is state change',
        AI_BOT_GET_NEW_STATE: 'Get new state',
        AI_BOT_GET_OLD_STATE: 'Get old state',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Idle',
        INITING: 'Initing',
        STANDBY: 'Standby',
        CONNECTING: 'Connecting',
        LISTENING: 'Listening',
        SPEAKING: 'Speaking',
        AI_BOT_EVENT_IS_EMOTION: 'If event is emotion',
        AI_BOT_GET_EMOTION: 'Get emotion',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'If event is chat message',
        AI_BOT_GET_CHAT_ROLE: 'Get chat role',
        AI_BOT_CHAT_ROLE_ENUM: 'Chat system role %1',
        AI_BOT_GET_CHAT_CONTENT: 'Get chat content',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'If is IOT control event',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'Get IOT event name',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'IOT event function is %1',
        AIBOT_UPDATE_IOT_STATE: 'Update device %1 status value %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'IOT is LED event function is %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'IOT is servo event function is %1',
        SETONESERVO: 'Set one servo',
        SETALLSERVOS: 'Set all servos',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Get IOT set servo %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Update LED device %1 status value %2',
        OPEN: 'Open',
        CLOSE: 'Close',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Update servo device %1 angle to %2',
        NUMBER:'Number',
        ANGLE:'Angle',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Update %1 servos angle to %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Update ultrasonic %1 distance to %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Update temperature and humidity %1 data to %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Update analog sensor %1 data %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Anzeige',
        REGISTER_CATEGORY: 'Hardware registrieren',
        EVENT_CATEGORY: 'Ereignis',
        STATE_CATEGORY: 'Gerät aktualisieren',
        AI_BOT_INIT_WIFI: 'AI-bot-Netzwerk initialisieren SSID %1 PASSWORT %2',
        AI_BOT_INIT_STD: 'AI-bot initialisieren %1 Mic BCLK %2 WS %3 DIN %4 %5 Lautsprecher BCLK %6 WS %7 DOUT %8 %9 Trigger-Pin %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED-Anzeige Status anzeigen %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED-Anzeige %1 Chat-Nachricht anzeigen %2',
        SYSTEM: 'System',
        ASSISANT: 'Assistent',
        USER: 'Benutzer',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED-Anzeige Emotion anzeigen %1',
        AI_BOT_INIT_OLED: 'OLED-Anzeige initialisieren %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Steuergerät registrieren %1 Eigenschaften: %2 Steuerfunktionen: Einschalten %3 Ausschalten %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'LED-Gerätenamen registrieren %1 LED-Anzahl %2 Eigenschaftsbeschreibung %3 Steuerfunktionen Ein %4 Aus %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Servogerät registrieren Name %1 Servomenge %2 Eigenschaftsbeschreibung %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Analogen Sensor registrieren Gerätename %1 Eigenschaftsbeschreibung %2 Status %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Ultraschallgerät registrieren Name %1 Eigenschaftsbeschreibung %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'DHT11-Gerät registrieren Temperaturfunktionsname %1 Eigenschaftsbeschreibung %2 Feuchtigkeitsfunktionsname %3 Eigenschaftsbeschreibung %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'WS2812-Farblicht Funktionsname registrieren %1 LED-Anzahl %2',
        AI_BOT_LOOP: 'Wenn AI-bot-Ereignis auftritt %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'Wenn Ereignis Aktivierung ist',
        DO: 'TUE %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Aktivierungsnachricht abrufen',
        AI_BOT_GET_ACTIVATION_CODE: 'Aktivierungscode abrufen',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'Wenn Ereignis Zustandsänderung ist',
        AI_BOT_GET_NEW_STATE: 'Neuen Zustand abrufen',
        AI_BOT_GET_OLD_STATE: 'Alten Zustand abrufen',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Leerlauf',
        INITING: 'Initialisierung',
        STANDBY: 'Bereitschaft',
        CONNECTING: 'Verbinden',
        LISTENING: 'Zuhören',
        SPEAKING: 'Sprechen',
        AI_BOT_EVENT_IS_EMOTION: 'Wenn Ereignis Emotion ist',
        AI_BOT_GET_EMOTION: 'Emotion abrufen',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'Wenn Ereignis Chat-Nachricht ist',
        AI_BOT_GET_CHAT_ROLE: 'Chat-Rolle abrufen',
        AI_BOT_CHAT_ROLE_ENUM: 'Chat-Systemrolle %1',
        AI_BOT_GET_CHAT_CONTENT: 'Chat-Inhalt abrufen',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'Wenn es ein IoT-Steuerereignis ist',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'IoT-Ereignisnamen abrufen',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'IoT-Ereignisfunktion ist %1',
        AIBOT_UPDATE_IOT_STATE: 'Gerät %1 Statuswert aktualisieren %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'IoT-LED-Ereignisfunktion ist %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'IoT-Servo-Ereignisfunktion ist %1',
        SETONESERVO: 'Einen Servo einstellen',
        SETALLSERVOS: 'Alle Servos einstellen',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'IoT-Servo einstellen abrufen %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'LED-Gerät %1 Statuswert aktualisieren %2',
        OPEN: 'Öffnen',
        CLOSE: 'Schließen',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Servogerät %1 Winkel auf %2 aktualisieren',
        NUMBER:'Zahl',
        ANGLE:'Winkel',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: '%1 Servos Winkel auf %2 aktualisieren',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Ultraschall %1 Entfernung auf %2 aktualisieren',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Temperatur und Luftfeuchtigkeit %1 Daten auf %2 aktualisieren',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Analogen Sensor %1 Daten %2 aktualisieren'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Pantalla',
        REGISTER_CATEGORY: 'Registrar hardware',
        EVENT_CATEGORY: 'Evento',
        STATE_CATEGORY: 'Actualizar dispositivo',
        AI_BOT_INIT_WIFI: 'Inicializar red de AI-bot SSID %1 CONTRASEÑA %2',
        AI_BOT_INIT_STD: 'Inicializar AI-bot %1 Mic BCLK %2 WS %3 DIN %4 %5 Altavoz BCLK %6 WS %7 DOUT %8 %9 pin de disparo %10',
        AI_BOT_OLED_SHOW_STATUS: 'Pantalla OLED mostrar estado %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'Pantalla OLED %1 mostrar mensaje de chat %2',
        SYSTEM: 'Sistema',
        ASSISANT: 'Asistente',
        USER: 'Usuario',
        AI_BOT_OLED_SHOW_EMOTION: 'Pantalla OLED mostrar emoción %1',
        AI_BOT_INIT_OLED: 'Inicializar pantalla OLED %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Registrar dispositivo de control %1 propiedades: %2 funciones de control: encender %3 apagar %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Registrar nombre de dispositivo LED %1 cantidad de LED %2 descripción de propiedades %3 funciones de control encender %4 apagar %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Registrar dispositivo servo nombre %1 cantidad de servos %2 descripción de propiedades %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Registrar sensor analógico nombre del dispositivo %1 descripción de propiedades %2 estado %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Registrar dispositivo ultrasónico nombre %1 descripción de propiedades %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Registrar dispositivo DHT11 nombre de función de temperatura %1 descripción de propiedades %2 nombre de función de humedad %3 descripción de propiedades %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Registrar luz de color WS2812 nombre de la función %1 cantidad de LED %2',
        AI_BOT_LOOP: 'Cuando ocurra un evento de AI-bot %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'Si el evento es activación',
        DO: 'HACER %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Obtener mensaje de activación',
        AI_BOT_GET_ACTIVATION_CODE: 'Obtener código de activación',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'Si el evento es cambio de estado',
        AI_BOT_GET_NEW_STATE: 'Obtener estado nuevo',
        AI_BOT_GET_OLD_STATE: 'Obtener estado anterior',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Inactivo',
        INITING: 'Iniciando',
        STANDBY: 'En espera',
        CONNECTING: 'Conectando',
        LISTENING: 'Escuchando',
        SPEAKING: 'Hablando',
        AI_BOT_EVENT_IS_EMOTION: 'Si el evento es emoción',
        AI_BOT_GET_EMOTION: 'Obtener emoción',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'Si el evento es mensaje de chat',
        AI_BOT_GET_CHAT_ROLE: 'Obtener rol de chat',
        AI_BOT_CHAT_ROLE_ENUM: 'Rol del sistema de chat %1',
        AI_BOT_GET_CHAT_CONTENT: 'Obtener contenido del chat',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'Si es un evento de control IoT',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'Obtener nombre del evento IoT',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'La función del evento IoT es %1',
        AIBOT_UPDATE_IOT_STATE: 'Actualizar valor de estado del dispositivo %1 a %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'La función del evento IoT para LED es %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'La función del evento IoT para servo es %1',
        SETONESERVO: 'Ajustar un servo',
        SETALLSERVOS: 'Ajustar todos los servos',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Obtener ajuste de servo IoT %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Actualizar estado del dispositivo LED %1 a %2',
        OPEN: 'Abrir',
        CLOSE: 'Cerrar',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Actualizar servo %1 ángulo a %2',
        NUMBER:'Número',
        ANGLE:'Ángulo',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Actualizar %1 servos ángulo a %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Actualizar ultrasónico %1 distancia a %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Actualizar temperatura y humedad %1 datos a %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Actualizar sensor analógico %1 datos %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Affichage',
        REGISTER_CATEGORY: 'Enregistrer le matériel',
        EVENT_CATEGORY: 'Événement',
        STATE_CATEGORY: 'Mettre à jour l’appareil',
        AI_BOT_INIT_WIFI: 'Initialiser le réseau AI-bot SSID %1 MOT DE PASSE %2',
        AI_BOT_INIT_STD: 'Initialiser AI-bot %1 Mic BCLK %2 WS %3 DIN %4 %5 Haut-parleur BCLK %6 WS %7 DOUT %8 %9 broche de déclenchement %10',
        AI_BOT_OLED_SHOW_STATUS: 'Écran OLED afficher l’état %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'Écran OLED %1 afficher le message de chat %2',
        SYSTEM: 'Système',
        ASSISANT: 'Assistant',
        USER: 'Utilisateur',
        AI_BOT_OLED_SHOW_EMOTION: 'Écran OLED afficher l’émotion %1',
        AI_BOT_INIT_OLED: 'Initialiser l’écran OLED %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Enregistrer l’appareil de contrôle %1 propriétés : %2 fonctions de contrôle : ouvrir %3 fermer %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Enregistrer le nom de l’appareil LED %1 nombre de LED %2 description des propriétés %3 fonctions de contrôle ouvrir %4 fermer %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Enregistrer l’appareil servo nom %1 nombre de servos %2 description des propriétés %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Enregistrer le capteur analogique nom de l’appareil %1 description des propriétés %2 état %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Enregistrer l’appareil à ultrasons nom %1 description des propriétés %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Enregistrer l’appareil DHT11 nom de la fonction température %1 description des propriétés %2 nom de la fonction humidité %3 description des propriétés %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Enregistrer la lumière colorée WS2812 nom de la fonction %1 nombre de LED %2',
        AI_BOT_LOOP: 'Lorsque l’événement AI-bot se produit %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'Si l’événement est une activation',
        DO: 'FAIRE %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Obtenir le message d’activation',
        AI_BOT_GET_ACTIVATION_CODE: 'Obtenir le code d’activation',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'Si l’événement est un changement d’état',
        AI_BOT_GET_NEW_STATE: 'Obtenir le nouvel état',
        AI_BOT_GET_OLD_STATE: 'Obtenir l’ancien état',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Inactif',
        INITING: 'Initialisation',
        STANDBY: 'Veille',
        CONNECTING: 'Connexion',
        LISTENING: 'Écoute',
        SPEAKING: 'Parole',
        AI_BOT_EVENT_IS_EMOTION: 'Si l’événement est une émotion',
        AI_BOT_GET_EMOTION: 'Obtenir l’émotion',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'Si l’événement est un message de chat',
        AI_BOT_GET_CHAT_ROLE: 'Obtenir le rôle de chat',
        AI_BOT_CHAT_ROLE_ENUM: 'Rôle du système de chat %1',
        AI_BOT_GET_CHAT_CONTENT: 'Obtenir le contenu du chat',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'S’il s’agit d’un événement de contrôle IoT',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'Obtenir le nom de l’événement IoT',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'La fonction de l’événement IoT est %1',
        AIBOT_UPDATE_IOT_STATE: 'Mettre à jour la valeur d’état de l’appareil %1 à %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'La fonction de l’événement IoT pour LED est %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'La fonction de l’événement IoT pour servo est %1',
        SETONESERVO: 'Régler un servo',
        SETALLSERVOS: 'Régler tous les servos',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Obtenir le réglage du servo IoT %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Mettre à jour l’appareil LED %1 valeur d’état à %2',
        OPEN: 'Ouvrir',
        CLOSE: 'Fermer',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Mettre à jour l’appareil servo %1 angle à %2',
        NUMBER:'Nombre',
        ANGLE:'Angle',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Mettre à jour %1 servos angle à %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Mettre à jour l’ultrason %1 distance à %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Mettre à jour température et humidité %1 données à %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Mettre à jour capteur analogique %1 données %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'ディスプレイ',
        REGISTER_CATEGORY: 'ハードウェア登録',
        EVENT_CATEGORY: 'イベント',
        STATE_CATEGORY: 'デバイス更新',
        AI_BOT_INIT_WIFI: 'AI-bot ネットワークを初期化 SSID %1 パスワード %2',
        AI_BOT_INIT_STD: 'AI-bot を初期化 %1 マイク BCLK %2 WS %3 DIN %4 %5 スピーカー BCLK %6 WS %7 DOUT %8 %9 トリガーピン %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED ディスプレイ 状態を表示 %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED ディスプレイ %1 チャットメッセージを表示 %2',
        SYSTEM: 'システム',
        ASSISANT: 'アシスタント',
        USER: 'ユーザー',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED ディスプレイ 感情を表示 %1',
        AI_BOT_INIT_OLED: 'OLED ディスプレイを初期化 %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: '制御デバイスを登録 %1 プロパティ: %2 制御機能: オン %3 オフ %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'LED デバイス名を登録 %1 LED 数 %2 プロパティ説明 %3 制御機能 オン %4 オフ %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'サーボデバイスを登録 名称 %1 サーボ数 %2 プロパティ説明 %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'アナログセンサーを登録 デバイス名 %1 プロパティ説明 %2 ステータス %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: '超音波デバイスを登録 名称 %1 プロパティ説明 %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'DHT11 デバイスを登録 温度機能名 %1 プロパティ説明 %2 湿度機能名 %3 プロパティ説明 %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'WS2812 カラーライト 機能名を登録 %1 LED 数 %2',
        AI_BOT_LOOP: 'AI-bot イベントが発生したとき %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'イベントがアクティベーションの場合',
        DO: '実行 %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'アクティベーションメッセージを取得',
        AI_BOT_GET_ACTIVATION_CODE: 'アクティベーションコードを取得',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'イベントが状態変化の場合',
        AI_BOT_GET_NEW_STATE: '新しい状態を取得',
        AI_BOT_GET_OLD_STATE: '以前の状態を取得',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'アイドル',
        INITING: '初期化中',
        STANDBY: '待機',
        CONNECTING: '接続中',
        LISTENING: 'リスニング',
        SPEAKING: '発話中',
        AI_BOT_EVENT_IS_EMOTION: 'イベントが感情の場合',
        AI_BOT_GET_EMOTION: '感情を取得',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'イベントがチャットメッセージの場合',
        AI_BOT_GET_CHAT_ROLE: 'チャット役割を取得',
        AI_BOT_CHAT_ROLE_ENUM: 'チャットシステムの役割 %1',
        AI_BOT_GET_CHAT_CONTENT: 'チャット内容を取得',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'IoT 制御イベントの場合',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'IoT イベント名を取得',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'IoT イベントの機能は %1',
        AIBOT_UPDATE_IOT_STATE: 'デバイス %1 の状態値を %2 に更新',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'IoT の LED イベント機能は %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'IoT のサーボイベント機能は %1',
        SETONESERVO: 'サーボを1つ設定',
        SETALLSERVOS: 'すべてのサーボを設定',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'IoT サーボ設定を取得 %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'LED デバイス %1 の状態値を %2 に更新',
        OPEN: '開く',
        CLOSE: '閉じる',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'サーボデバイス %1 角度を %2 に更新',
        NUMBER:'数値',
        ANGLE:'角度',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: '%1 個のサーボの角度を %2 に更新',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: '超音波 %1 距離を %2 に更新',
        AI_BOT_UPDATE_DHT11_IOT_STATE: '温湿度 %1 データを %2 に更新',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'アナログセンサー %1 データ %2 を更新'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: '디스플레이',
        REGISTER_CATEGORY: '하드웨어 등록',
        EVENT_CATEGORY: '이벤트',
        STATE_CATEGORY: '장치 업데이트',
        AI_BOT_INIT_WIFI: 'AI-bot 네트워크 초기화 SSID %1 비밀번호 %2',
        AI_BOT_INIT_STD: 'AI-bot 초기화 %1 마이크 BCLK %2 WS %3 DIN %4 %5 스피커 BCLK %6 WS %7 DOUT %8 %9 트리거 핀 %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED 디스플레이 상태 표시 %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED 디스플레이 %1 채팅 메시지 표시 %2',
        SYSTEM: '시스템',
        ASSISANT: '어시스턴트',
        USER: '사용자',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED 디스플레이 감정 표시 %1',
        AI_BOT_INIT_OLED: 'OLED 디스플레이 초기화 %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: '제어 장치 등록 %1 속성: %2 제어 기능: 켜기 %3 끄기 %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'LED 장치 이름 등록 %1 LED 개수 %2 속성 설명 %3 제어 기능 켜기 %4 끄기 %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: '서보 장치 등록 이름 %1 서보 개수 %2 속성 설명 %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: '아날로그 센서 등록 장치 이름 %1 속성 설명 %2 상태 %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: '초음파 장치 등록 이름 %1 속성 설명 %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'DHT11 장치 등록 온도 기능 이름 %1 속성 설명 %2 습도 기능 이름 %3 속성 설명 %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'WS2812 컬러 라이트 기능 이름 등록 %1 LED 개수 %2',
        AI_BOT_LOOP: 'AI-bot 이벤트 발생 시 %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: '이벤트가 활성화인 경우',
        DO: '실행 %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: '활성화 메시지 가져오기',
        AI_BOT_GET_ACTIVATION_CODE: '활성화 코드 가져오기',
        AI_BOT_EVENT_IS_STATE_CHANGE: '이벤트가 상태 변경인 경우',
        AI_BOT_GET_NEW_STATE: '새 상태 가져오기',
        AI_BOT_GET_OLD_STATE: '이전 상태 가져오기',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: '대기',
        INITING: '초기화 중',
        STANDBY: '대기 모드',
        CONNECTING: '연결 중',
        LISTENING: '청취 중',
        SPEAKING: '발화 중',
        AI_BOT_EVENT_IS_EMOTION: '이벤트가 감정인 경우',
        AI_BOT_GET_EMOTION: '감정 가져오기',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: '이벤트가 채팅 메시지인 경우',
        AI_BOT_GET_CHAT_ROLE: '채팅 역할 가져오기',
        AI_BOT_CHAT_ROLE_ENUM: '채팅 시스템 역할 %1',
        AI_BOT_GET_CHAT_CONTENT: '채팅 내용 가져오기',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'IoT 제어 이벤트인 경우',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'IoT 이벤트 이름 가져오기',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'IoT 이벤트 기능은 %1',
        AIBOT_UPDATE_IOT_STATE: '장치 %1 상태 값을 %2로 업데이트',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'IoT의 LED 이벤트 기능은 %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'IoT의 서보 이벤트 기능은 %1',
        SETONESERVO: '서보 하나 설정',
        SETALLSERVOS: '모든 서보 설정',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'IoT 서보 설정 값 가져오기 %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'LED 장치 %1 상태 값을 %2로 업데이트',
        OPEN: '열기',
        CLOSE: '닫기',
        AI_BOT_UPDATE_SERVO_IOT_STATE: '서보 장치 %1 각도를 %2로 업데이트',
        NUMBER:'숫자',
        ANGLE:'각도',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: '%1개의 서보 각도를 %2로 업데이트',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: '초음파 %1 거리를 %2로 업데이트',
        AI_BOT_UPDATE_DHT11_IOT_STATE: '온습도 %1 데이터를 %2로 업데이트',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: '아날로그 센서 %1 데이터 %2 업데이트'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Wyświetlacz',
        REGISTER_CATEGORY: 'Rejestracja sprzętu',
        EVENT_CATEGORY: 'Zdarzenie',
        STATE_CATEGORY: 'Aktualizacja urządzenia',
        AI_BOT_INIT_WIFI: 'Inicjalizuj sieć AI-bot SSID %1 HASŁO %2',
        AI_BOT_INIT_STD: 'Zainicjuj AI-bot %1 Mikrofon BCLK %2 WS %3 DIN %4 %5 Głośnik BCLK %6 WS %7 DOUT %8 %9 pin wyzwalający %10',
        AI_BOT_OLED_SHOW_STATUS: 'Wyświetlacz OLED pokaż status %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'Wyświetlacz OLED %1 pokaż wiadomość czatu %2',
        SYSTEM: 'System',
        ASSISANT: 'Asystent',
        USER: 'Użytkownik',
        AI_BOT_OLED_SHOW_EMOTION: 'Wyświetlacz OLED pokaż emocję %1',
        AI_BOT_INIT_OLED: 'Zainicjuj wyświetlacz OLED %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Zarejestruj urządzenie sterujące %1 właściwości: %2 funkcje sterowania: włącz %3 wyłącz %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Zarejestruj nazwę urządzenia LED %1 liczba LED %2 opis właściwości %3 funkcje sterowania włącz %4 wyłącz %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Zarejestruj urządzenie serwo nazwa %1 liczba serw %2 opis właściwości %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Zarejestruj czujnik analogowy nazwa urządzenia %1 opis właściwości %2 status %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Zarejestruj urządzenie ultradźwiękowe nazwa %1 opis właściwości %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Zarejestruj urządzenie DHT11 nazwa funkcji temperatury %1 opis właściwości %2 nazwa funkcji wilgotności %3 opis właściwości %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Zarejestruj kolorowe światło WS2812 nazwa funkcji %1 liczba LED %2',
        AI_BOT_LOOP: 'Gdy wystąpi zdarzenie AI-bot %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'Jeśli zdarzenie to aktywacja',
        DO: 'WYKONAJ %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Pobierz wiadomość aktywacyjną',
        AI_BOT_GET_ACTIVATION_CODE: 'Pobierz kod aktywacyjny',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'Jeśli zdarzenie to zmiana stanu',
        AI_BOT_GET_NEW_STATE: 'Pobierz nowy stan',
        AI_BOT_GET_OLD_STATE: 'Pobierz poprzedni stan',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Bezczynność',
        INITING: 'Inicjalizowanie',
        STANDBY: 'Tryb gotowości',
        CONNECTING: 'Łączenie',
        LISTENING: 'Słuchanie',
        SPEAKING: 'Mówienie',
        AI_BOT_EVENT_IS_EMOTION: 'Jeśli zdarzenie to emocja',
        AI_BOT_GET_EMOTION: 'Pobierz emocję',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'Jeśli zdarzenie to wiadomość czatu',
        AI_BOT_GET_CHAT_ROLE: 'Pobierz rolę czatu',
        AI_BOT_CHAT_ROLE_ENUM: 'Rola systemu czatu %1',
        AI_BOT_GET_CHAT_CONTENT: 'Pobierz treść czatu',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'Jeśli to zdarzenie sterowania IoT',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'Pobierz nazwę zdarzenia IoT',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'Funkcja zdarzenia IoT to %1',
        AIBOT_UPDATE_IOT_STATE: 'Zaktualizuj wartość stanu urządzenia %1 do %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'Funkcja zdarzenia IoT dla LED to %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'Funkcja zdarzenia IoT dla serwa to %1',
        SETONESERVO: 'Ustaw jedno serwo',
        SETALLSERVOS: 'Ustaw wszystkie serwa',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Pobierz ustawienie serwa IoT %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Zaktualizuj urządzenie LED %1 wartość stanu do %2',
        OPEN: 'Otwórz',
        CLOSE: 'Zamknij',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Zaktualizuj urządzenie serwo %1 kąt do %2',
        NUMBER:'Liczba',
        ANGLE:'Kąt',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Zaktualizuj %1 serw kąt do %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Zaktualizuj ultradźwięk %1 odległość do %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Zaktualizuj temperaturę i wilgotność %1 dane do %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Zaktualizuj czujnik analogowy %1 dane %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Exibição',
        REGISTER_CATEGORY: 'Registrar hardware',
        EVENT_CATEGORY: 'Evento',
        STATE_CATEGORY: 'Atualizar dispositivo',
        AI_BOT_INIT_WIFI: 'Inicializar rede do AI-bot SSID %1 SENHA %2',
        AI_BOT_INIT_STD: 'Inicializar AI-bot %1 Mic BCLK %2 WS %3 DIN %4 %5 Alto-falante BCLK %6 WS %7 DOUT %8 %9 pino de gatilho %10',
        AI_BOT_OLED_SHOW_STATUS: 'Tela OLED mostrar status %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'Tela OLED %1 mostrar mensagem do chat %2',
        SYSTEM: 'Sistema',
        ASSISANT: 'Assistente',
        USER: 'Usuário',
        AI_BOT_OLED_SHOW_EMOTION: 'Tela OLED mostrar emoção %1',
        AI_BOT_INIT_OLED: 'Inicializar tela OLED %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Registrar dispositivo de controle %1 propriedades: %2 funções de controle: abrir %3 fechar %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Registrar dispositivo LED nome %1 quantidade de LEDs %2 descrição das propriedades %3 funções de controle abrir %4 fechar %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Registrar dispositivo servo nome %1 quantidade de servos %2 descrição das propriedades %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Registrar sensor analógico nome do dispositivo %1 descrição das propriedades %2 status %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Registrar dispositivo ultrassônico nome %1 descrição das propriedades %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Registrar dispositivo DHT11 nome da função de temperatura %1 descrição das propriedades %2 nome da função de umidade %3 descrição das propriedades %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Registrar luz colorida WS2812 nome da função %1 quantidade de LEDs %2',
        AI_BOT_LOOP: 'Quando ocorrer evento do AI-bot %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'Se o evento for ativação',
        DO: 'FAZER %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Obter mensagem de ativação',
        AI_BOT_GET_ACTIVATION_CODE: 'Obter código de ativação',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'Se o evento for mudança de estado',
        AI_BOT_GET_NEW_STATE: 'Obter novo estado',
        AI_BOT_GET_OLD_STATE: 'Obter estado anterior',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Ocioso',
        INITING: 'Inicializando',
        STANDBY: 'Em espera',
        CONNECTING: 'Conectando',
        LISTENING: 'Ouvindo',
        SPEAKING: 'Falando',
        AI_BOT_EVENT_IS_EMOTION: 'Se o evento for emoção',
        AI_BOT_GET_EMOTION: 'Obter emoção',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'Se o evento for mensagem de chat',
        AI_BOT_GET_CHAT_ROLE: 'Obter função no chat',
        AI_BOT_CHAT_ROLE_ENUM: 'Função do sistema de chat %1',
        AI_BOT_GET_CHAT_CONTENT: 'Obter conteúdo do chat',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'Se for um evento de controle de IoT',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'Obter nome do evento de IoT',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'A função do evento de IoT é %1',
        AIBOT_UPDATE_IOT_STATE: 'Atualizar valor de status do dispositivo %1 para %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'A função do evento de IoT para LED é %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'A função do evento de IoT para servo é %1',
        SETONESERVO: 'Ajustar um servo',
        SETALLSERVOS: 'Ajustar todos os servos',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Obter configuração de servo IoT %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Atualizar dispositivo LED %1 valor de status para %2',
        OPEN: 'Abrir',
        CLOSE: 'Fechar',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Atualizar dispositivo servo %1 ângulo para %2',
        NUMBER:'Número',
        ANGLE:'Ângulo',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Atualizar %1 servos ângulo para %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Atualizar ultrassônico %1 distância para %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Atualizar temperatura e umidade %1 dados para %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Atualizar sensor analógico %1 dados %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Дисплей',
        REGISTER_CATEGORY: 'Регистрация оборудования',
        EVENT_CATEGORY: 'Событие',
        STATE_CATEGORY: 'Обновить устройство',
        AI_BOT_INIT_WIFI: 'Инициализировать сеть AI-bot SSID %1 ПАРОЛЬ %2',
        AI_BOT_INIT_STD: 'Инициализировать AI-bot %1 Микрофон BCLK %2 WS %3 DIN %4 %5 Динамик BCLK %6 WS %7 DOUT %8 %9 пин триггера %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED-дисплей показать статус %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED-дисплей %1 показать сообщение чата %2',
        SYSTEM: 'Система',
        ASSISANT: 'Ассистент',
        USER: 'Пользователь',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED-дисплей показать эмоцию %1',
        AI_BOT_INIT_OLED: 'Инициализировать OLED-дисплей %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Зарегистрировать управляющее устройство %1 свойства: %2 функции управления: включить %3 выключить %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Зарегистрировать устройство LED имя %1 количество светодиодов %2 описание свойств %3 функции управления включить %4 выключить %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Зарегистрировать сервоустройство имя %1 количество сервоприводов %2 описание свойств %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Зарегистрировать аналоговый датчик имя устройства %1 описание свойств %2 статус %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Зарегистрировать ультразвуковое устройство имя %1 описание свойств %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Зарегистрировать устройство DHT11 имя функции температуры %1 описание свойств %2 имя функции влажности %3 описание свойств %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Зарегистрировать цветной свет WS2812 имя функции %1 количество светодиодов %2',
        AI_BOT_LOOP: 'Когда происходит событие AI-bot %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: 'Если событие — активация',
        DO: 'ВЫПОЛНИТЬ %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: 'Получить сообщение активации',
        AI_BOT_GET_ACTIVATION_CODE: 'Получить код активации',
        AI_BOT_EVENT_IS_STATE_CHANGE: 'Если событие — изменение состояния',
        AI_BOT_GET_NEW_STATE: 'Получить новое состояние',
        AI_BOT_GET_OLD_STATE: 'Получить старое состояние',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Простой',
        INITING: 'Инициализация',
        STANDBY: 'Режим ожидания',
        CONNECTING: 'Подключение',
        LISTENING: 'Прослушивание',
        SPEAKING: 'Разговор',
        AI_BOT_EVENT_IS_EMOTION: 'Если событие — эмоция',
        AI_BOT_GET_EMOTION: 'Получить эмоцию',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: 'Если событие — сообщение чата',
        AI_BOT_GET_CHAT_ROLE: 'Получить роль чата',
        AI_BOT_CHAT_ROLE_ENUM: 'Роль системы чата %1',
        AI_BOT_GET_CHAT_CONTENT: 'Получить содержание чата',
        AI_BOT_EVENT_IS_IOT_MESSAGE: 'Если это событие управления IoT',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: 'Получить название события IoT',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'Функция события IoT — %1',
        AIBOT_UPDATE_IOT_STATE: 'Обновить состояние устройства %1 до значения %2',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'Функция события IoT для LED — %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'Функция события IoT для серво — %1',
        SETONESERVO: 'Настроить один серво',
        SETALLSERVOS: 'Настроить все серво',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Получить настройку серво IoT %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Обновить устройство LED %1 значение состояния до %2',
        OPEN: 'Открыть',
        CLOSE: 'Закрыть',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Обновить сервоустройство %1 угол до %2',
        NUMBER:'Число',
        ANGLE:'Угол',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Обновить %1 серво угол до %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Обновить ультразвук %1 расстояние до %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Обновить температуру и влажность %1 данные до %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Обновить аналоговый датчик %1 данные %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: '顯示',
        REGISTER_CATEGORY: '註冊硬體',
        EVENT_CATEGORY: '事件',
        STATE_CATEGORY: '更新裝置',
        AI_BOT_INIT_WIFI: '初始化 AI-bot 網路 SSID %1 密碼 %2',
        AI_BOT_INIT_STD: '初始化 AI-bot %1 麥克風 BCLK %2 WS %3 DIN %4 %5 揚聲器 BCLK %6 WS %7 DOUT %8 %9 觸發腳位 %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED 顯示器 顯示狀態 %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED 顯示器 %1 顯示聊天訊息 %2',
        SYSTEM: '系統',
        ASSISANT: '助手',
        USER: '使用者',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED 顯示器 顯示表情 %1',
        AI_BOT_INIT_OLED: '初始化 OLED 顯示器 %1 SDA %2 SCL %3 ',
        AIBOT_REGISTER_DRIVER_STATUS: '註冊控制裝置 %1 屬性：%2 控制功能： 開啟 %3 關閉 %4 ',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: '註冊 LED 裝置名稱 %1 LED 數量 %2 屬性描述 %3 控制功能 開啟 %4 關閉 %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: '註冊伺服裝置名稱 %1 伺服數量 %2 屬性描述 %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: '註冊類比感測器裝置名稱 %1 屬性描述 %2 狀態 %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: '註冊超音波裝置名稱 %1 屬性描述 %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: '註冊溫溼度 DHT11 裝置 溫度功能名稱 %1 屬性描述 %2 溼度功能名稱 %3 屬性描述 %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: '註冊 WS2812 彩燈功能名稱 %1 燈珠數量 %2',
        AI_BOT_LOOP: '當 AI-bot 事件發生時 %1 %2',
        DO: '執行 %1',
        AI_BOT_EVENT_IS_ACTIVATION: '如果事件是 啟動',
        // 注：此條來自 message1，但你目標清單包含類似鍵，保留 message0 提取要求，這裡僅列出 message0 部分
        AI_BOT_GET_ACTIVATION_MESSAGE: '取得啟動訊息',
        AI_BOT_GET_ACTIVATION_CODE: '取得啟動代碼',
        AI_BOT_EVENT_IS_STATE_CHANGE: '如果事件是 狀態變更',
        AI_BOT_GET_NEW_STATE: '取得新狀態',
        AI_BOT_GET_OLD_STATE: '取得舊狀態',
        AI_BOT_STATE_ENUM: '%1',
        AI_BOT_EVENT_IS_EMOTION: '如果事件是 表情',
        AI_BOT_GET_EMOTION: '取得表情',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: '如果事件是 聊天訊息',
        AI_BOT_GET_CHAT_ROLE: '取得聊天角色',
        AI_BOT_CHAT_ROLE_ENUM: '聊天系統角色 %1',
        IDLE: '閒置中',
        INITING: '初始化中',
        STANDBY: '待命中',
        CONNECTING: '連線中',
        LISTENING: '聆聽中',
        SPEAKING: '說話中',
        AI_BOT_GET_CHAT_CONTENT: '取得聊天內容',
        AI_BOT_EVENT_IS_IOT_MESSAGE: '如果是 IoT 控制事件',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: '取得 IoT 事件名稱',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'IoT 事件功能為 %1',
        AIBOT_UPDATE_IOT_STATE: '更新裝置 %1 狀態值 %2 ',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'IoT 為 LED 事件功能為 %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'IoT 為伺服事件功能為 %1',
        SETONESERVO: '設定單個伺服',
        SETALLSERVOS: '設定所有伺服',
        AI_BOT_GET_IOT_SERVO_MESSAGE: '取得 IoT 設定伺服的 %1',
        NUMBER:'編號',
        ANGLE:'角度',
        AI_BOT_UPDATE_LED_IOT_STATE: '更新 LED 裝置 %1 狀態值 %2',
        OPEN: '開啟',
        CLOSE: '關閉',
        AI_BOT_UPDATE_SERVO_IOT_STATE: '更新伺服裝置 %1 角度為 %2',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: '更新 %1 個伺服角度為 %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: '更新超音波 %1 距離為 %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: '更新溫溼度 %1 資料為 %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: '更新類比感測器 %1 資料 %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: '显示',
        REGISTER_CATEGORY: '注册硬件',
        EVENT_CATEGORY: '事件',
        STATE_CATEGORY: '更新设备',
        AI_BOT_INIT_WIFI: '初始化 AI-bot 网络 SSID %1 PASSWORD %2',
        AI_BOT_INIT_STD: '初始化 AI-bot %1 Mic BCLK %2 WS %3 DIN %4 %5 Speaker BCLK %6 WS %7 DOUT %8 %9 触发引脚 %10',
        AI_BOT_OLED_SHOW_STATUS: 'OLED显示屏 显示状态 %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'OLED显示屏 %1 显示聊天信息 %2',
        SYSTEM: '系统',
        ASSISANT: '助手',
        USER: '用户',
        AI_BOT_OLED_SHOW_EMOTION: 'OLED显示屏 显示表情 %1',
        AI_BOT_INIT_OLED: '初始化 OLED显示屏 %1 SDA %2 SCL %3 ',
        AIBOT_REGISTER_DRIVER_STATUS: '注册控制设备 %1 属性：%2 控制功能： 打开 %3 关闭 %4 ',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: '注册LED设备名称 %1 led数量 %2 属性描述 %3 控制功能 打开 %4 关闭 %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: '注册舵机设备名称 %1 舵机数量 %2 属性描述 %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: '注册模拟传感器设备名称 %1 属性描述 %2 状态 %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: '注册超声波设备名称 %1 属性描述 %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: '注册温湿度DHT11设备温度功能名称 %1 属性描述 %2 湿度功能名称 %3 属性描述 %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: '注册WS2812彩灯功能名称 %1 灯珠数量 %2',
        AI_BOT_LOOP: '当 AI-bot 事件发生时 %1 %2',
        DO: '执行 %1',
        AI_BOT_EVENT_IS_ACTIVATION: '如果事件是 激活',
        // 注：此条来自 message1，但你目标清单包含类似键，保留 message0 提取要求，这里仅列出 message0 部分
        AI_BOT_GET_ACTIVATION_MESSAGE: '获取激活消息',
        AI_BOT_GET_ACTIVATION_CODE: '获取激活代码',
        AI_BOT_EVENT_IS_STATE_CHANGE: '如果事件是 状态改变',
        AI_BOT_GET_NEW_STATE: '获取新状态',
        AI_BOT_GET_OLD_STATE: '获取旧状态',
        AI_BOT_STATE_ENUM: '%1',
        AI_BOT_EVENT_IS_EMOTION: '如果事件是 表情',
        AI_BOT_GET_EMOTION: '获取表情',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: '如果事件是 聊天消息',
        AI_BOT_GET_CHAT_ROLE: '获取聊天角色',
        AI_BOT_CHAT_ROLE_ENUM: '聊天系统角色 %1',
        IDLE: '空闲中',
        INITING: '初始化中',
        STANDBY: '待命中',
        CONNECTING: '连接中',
        LISTENING: '聆听中',
        SPEAKING: '说话中',
        AI_BOT_GET_CHAT_CONTENT: '获取聊天内容',
        AI_BOT_EVENT_IS_IOT_MESSAGE: '如果是IOT控制事件',
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: '获取IOT事件名称',
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: 'IOT事件功能为 %1',
        AIBOT_UPDATE_IOT_STATE: '更新设备 %1 状态值 %2 ',
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: 'IOT为LED事件功能为 %1',
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: 'IOT为舵机事件功能为 %1',
        SETONESERVO: '设置单个舵机',
        SETALLSERVOS: '设置所有舵机',
        AI_BOT_GET_IOT_SERVO_MESSAGE: '获取IOT设置舵机的 %1',
        NUMBER:'编号',
        ANGLE:'角度',
        AI_BOT_UPDATE_LED_IOT_STATE: '更新LED设备 %1 状态值 %2',
        OPEN: '打开',
        CLOSE: '关闭',
        AI_BOT_UPDATE_SERVO_IOT_STATE: '更新舵机设备 %1 角度为 %2',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: '更新 %1个舵机角度为 %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: '更新超声波%1 距离为 %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: '更新温湿度%1 数据为 %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: '更新模拟传感器 %1 数据 %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        AI_BOT_CATEGORY: 'AI-bot',
        DISPLAY_CATEGORY: 'Display',
        REGISTER_CATEGORY: 'Registrare hardware',
        EVENT_CATEGORY: 'Evento',
        STATE_CATEGORY: 'Aggiorna dispositivo',
        AI_BOT_INIT_WIFI: 'Inizializzare rete AI-bot SSID %1 PASSWORD %2',
        AI_BOT_INIT_STD: 'Inizializzare AI-bot %1 Mic BCLK %2 WS %3 DIN %4 %5 Altoparlante BCLK %6 WS %7 DOUT %8 %9 pin di trigger %10',
        AI_BOT_OLED_SHOW_STATUS: 'Schermo OLED mostra stato %1',
        AI_BOT_OLED_SHOW_CHAT_MESSAGE: 'Schermo OLED %1 mostra messaggio chat %2',
        SYSTEM: 'Sistema',
        ASSISANT: 'Assistente',
        USER: 'Utente',
        AI_BOT_OLED_SHOW_EMOTION: 'Schermo OLED mostra emozione %1',
        AI_BOT_INIT_OLED: 'Inizializzare schermo OLED %1 SDA %2 SCL %3',
        AIBOT_REGISTER_DRIVER_STATUS: 'Registrare dispositivo di controllo %1 proprietà: %2 funzioni di controllo: accendi %3 spegni %4',
        AI_BOT_REGISTER_LED_DRIVER_STATUS: 'Registrare dispositivo LED nome %1 numero di LED %2 descrizione proprietà %3 funzioni di controllo accendi %4 spegni %5',
        AI_BOT_REGISTER_SERVO_DRIVER_STATUS: 'Registrare dispositivo servo nome %1 numero di servo %2 descrizione proprietà %3',
        AI_BOT_REGISTER_ANALOG_SENSOR_DRIVER_STATUS: 'Registrare sensore analogico nome dispositivo %1 descrizione proprietà %2 stato %3',
        AI_BOT_REGISTER_ULTRASONIC_SENSOR_DRIVER_STATUS: 'Registrare dispositivo a ultrasuoni nome %1 descrizione proprietà %2',
        AI_BOT_REGISTER_DHT11_SENSOR_DRIVER_STATUS: 'Registrare dispositivo DHT11 nome funzione temperatura %1 descrizione proprietà %2 nome funzione umidità %3 descrizione proprietà %4',
        AI_BOT_REGISTER_WS2812_DRIVER_STATUS: 'Registrare luce colorata WS2812 nome funzione %1 numero di LED %2',
        AI_BOT_LOOP: 'Quando si verifica evento AI-bot %1 %2',
        AI_BOT_EVENT_IS_ACTIVATION: "Se l'evento è attivazione",
        DO: 'ESEGUI %1',
        AI_BOT_GET_ACTIVATION_MESSAGE: "Ottieni messaggio d'attivazione",
        AI_BOT_GET_ACTIVATION_CODE: "Ottieni codice d'attivazione",
        AI_BOT_EVENT_IS_STATE_CHANGE: "Se l'evento è cambio di stato",
        AI_BOT_GET_NEW_STATE: 'Ottieni nuovo stato',
        AI_BOT_GET_OLD_STATE: 'Ottieni stato precedente',
        AI_BOT_STATE_ENUM: '%1',
        IDLE: 'Inattivo',
        INITING: 'Inizializzazione',
        STANDBY: 'Standby',
        CONNECTING: 'Connessione',
        LISTENING: 'Ascolto',
        SPEAKING: 'Parlare',
        AI_BOT_EVENT_IS_EMOTION: "Se l'evento è emozione",
        AI_BOT_GET_EMOTION: 'Ottieni emozione',
        AI_BOT_EVENT_IS_CHAT_MESSAGE: "Se l'evento è messaggio di chat",
        AI_BOT_GET_CHAT_ROLE: 'Ottieni ruolo chat',
        AI_BOT_CHAT_ROLE_ENUM: 'Ruolo del sistema di chat %1',
        AI_BOT_GET_CHAT_CONTENT: 'Ottieni contenuto della chat',
        AI_BOT_EVENT_IS_IOT_MESSAGE: "Se è un evento di controllo IoT",
        AI_BOT_GET_IOT_MESSAGE_EVENT_NAME: "Ottieni nome dell'evento IoT",
        AIBOT_GET_IOT_MESSAGE_EVENT_FUNCTION: "La funzione dell'evento IoT è %1",
        AIBOT_UPDATE_IOT_STATE: "Aggiorna valore di stato del dispositivo %1 a %2",
        AI_BOT_GET_IOT_LED_MESSAGE_EVENT_FUNCTION: "La funzione dell'evento IoT per LED è %1",
        AI_BOT_GET_IOT_SERVO_MESSAGE_EVENT_FUNCTION: "La funzione dell'evento IoT per servo è %1",
        SETONESERVO: 'Imposta un servo',
        SETALLSERVOS: 'Imposta tutti i servo',
        AI_BOT_GET_IOT_SERVO_MESSAGE: 'Ottieni impostazione servo IoT %1',
        AI_BOT_UPDATE_LED_IOT_STATE: 'Aggiorna dispositivo LED %1 valore di stato a %2',
        OPEN: 'Apri',
        CLOSE: 'Chiudi',
        AI_BOT_UPDATE_SERVO_IOT_STATE: 'Aggiorna dispositivo servo %1 angolo a %2',
        NUMBER:'Numero',
        ANGLE:'Angolo',
        AI_BOT_UPDATE_ALL_SERVO_IOT_STATE: 'Aggiorna %1 servo angolo a %2',
        AI_BOT_UPDATE_ULTRASONIC_IOT_STATE: 'Aggiorna ultrasuoni %1 distanza a %2',
        AI_BOT_UPDATE_DHT11_IOT_STATE: 'Aggiorna temperatura e umidità %1 dati a %2',
        AI_BOT_UPDATE_ANALOG_SENSOR_IOT_STATE: 'Aggiorna sensore analogico %1 dati %2'  
    });

return Blockly;
}

exports = addMsg;
