/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'Runtime (milliseconds)',
        KS_MICROS: 'Runtime (microseconds)',

        ROBOT_CATEGORY: 'Run',
        ROBOT_FORWARD: 'Robot forward left motor speed%1 right motor speed%2',
        ROBOT_BACK: 'Robot back left motor speed%1 right motor speed%2',
        ROBOT_LEFT: 'Robot turn left left motor speed%1 right motor speed%2',
        ROBOT_RIGHT: 'Robot turn right left motor speed%1 right motor speed%2',
        ROBOT_STOP: 'Robot stop',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_DIGITAL: 'Motor INA#%1 State%2 INB#%3 State%4',
        MOTOR130_ANALOG: 'Motor INA#%1 State%2 INB#%3 analogWrite%4',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren Sie %1 Variablentyp %2 Name %3 Zugewiesen an %4',
        KS_variables_set:'Variable %1 um %2 setzen',
        KS_variables_change:'Variablenmodus %1 %2 ändern',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable um %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'lang',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'Zeichenfolge',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'Wort',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'Laufzeit (Millisekunden)',
        KS_MICROS: 'Laufzeit (Mikrosekunden)',

        ROBOT_CATEGORY: 'Fahrt',
        ROBOT_FORWARD: 'Roboter vorwärts linker Motor %1 rechter Motor %2',
        ROBOT_BACK: 'Roboter rückwärts linker Motor %1 rechter Motor %2',
        ROBOT_LEFT: 'Roboter links linker Motor %1 rechter Motor %2',
        ROBOT_RIGHT: 'Roboter rechts linker Motor %1 rechter Motor %2',
        ROBOT_STOP: 'Roboter stop',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_DIGITAL: 'Motor INA#%1 Status%2 INB#%3 Status%4',
        MOTOR130_ANALOG: 'Motor INA#%1 State%2 INB#%3 analogWrite%4',
        HC_SR04_CATEGORY: 'Ultraschall',
        HC_SR04_READ_DISTANCE: 'HC-SR04 Trig-Pin %1 Echo-Pin %2 Leseabstand %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable por %2',
        KS_variables_change:'Cambiar %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena por %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'largo',
        KS_MATH_FLOAT: 'flotante',
        KS_MATH_BOOLEAN: 'booleano',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'carácter',
        KS_MATH_STRING: 'cadena',
        KS_MATH_UNSIGNED_INT: 'int sin firmar',
        KS_MATH_WORD: 'palabra',
        KS_MATH_UNSIGNED_LONG: 'largo sin firmar',
        KS_MATH_UNSIGNED_CHAR: 'caracter sin firmar',
        KS_MATH_DOUBLE: 'doble',

        KS_TEXT_LABEL:'TEXTO',
        KS_char: 'char%1',
        KS_string: 'cadena%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Temporizador',
        KS_MILLIS: 'Tiempo de ejecución (milisegundos)',
        KS_MICROS: 'Tiempo de ejecución (microsegundos)',

        ROBOT_CATEGORY: 'Paseo',
        ROBOT_FORWARD: 'Robot adelante motor izq%1 motor der%2',
        ROBOT_BACK: 'Robot atrás motor izq%1 motor der%2',
        ROBOT_LEFT: 'Robot gira izquierda motor izq%1 motor der%2',
        ROBOT_RIGHT: 'Robot gira derecha motor izq%1 motor der%2',
        ROBOT_STOP: 'Parada del robot',
        MOTOR130_CATEGORY: 'Motor',
        MOTOR130_DIGITAL: 'Motor INA#%1 Estado%2 INB#%3 Estado%4',
        MOTOR130_ANALOG: 'Motor INA#%1 Estado%2 INB#%3 analogWrite%4',
        HC_SR04_CATEGORY: 'Ultrasónico',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin de activación %1 pin de eco %2 distancia de lectura %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
         KS_variables_declare:'Déclarer %1 variable Type %2 Nom %3 Attribué à %4',
         KS_variables_set: 'Définir la variable %1 par %2',
         KS_variables_change:'Changer %1 mode variable %2',
         KS_variables_value: 'variable %1',
         KS_variables_setString: 'Définir la variable chaîne %1 par %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'entier',
         KS_MATH_LONG: 'long',
         KS_MATH_FLOAT: 'flottant',
         KS_MATH_BOOLEAN: 'booléen',
         KS_MATH_BYTE: 'octet',
         KS_MATH_CHAR: 'car',
         KS_MATH_STRING: 'chaîne',
         KS_MATH_UNSIGNED_INT: 'entier non signé',
         KS_MATH_WORD: 'mot',
         KS_MATH_UNSIGNED_LONG: 'long non signé',
         KS_MATH_UNSIGNED_CHAR: 'caractère non signé',
         KS_MATH_DOUBLE: 'doubler',

         KS_TEXT_LABEL:'TEXTE',
         KS_char: 'car%1',
         KS_string: 'chaîne%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'logique',
         KS_judge:'%1 %2 %3',
         KS_TIME_LABEL:'Minuteur',
         KS_MILLIS: 'Durée de fonctionnement (millisecondes)',
         KS_MICROS: 'Durée de fonctionnement (microsecondes)',
         ROBOT_CATEGORY:'Conduire',
         ROBOT_FORWARD: 'Robot en avant moteur gauche%1 moteur droit%2',
         ROBOT_BACK: 'Robot en arrière moteur gauche%1 moteur droit%2',
         ROBOT_LEFT: 'Robot tourne à gauche moteur gauche%1 moteur droit%2',
         ROBOT_RIGHT: 'Robot tourne à droite moteur gauche%1 moteur droit%2',
         ROBOT_STOP: 'Arrêt du robot',

         MOTOR130_CATEGORY: 'Moteur',
         MOTOR130_DIGITAL: 'Moteur INA#%1 État%2 INB#%3 État%4',
         MOTOR130_ANALOG: 'Moteur INA#%1 État%2 INB#%3 analogWrite%4',
         HC_SR04_CATEGORY: 'Ultrasons',
         HC_SR04_READ_DISTANCE: 'broche de déclenchement HC-SR04 %1 broche d"écho %2 distance de lecture %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数タイプ',
         KS_variables_declare:'%1 変数を宣言します。タイプ %2 名前 %3 を %4 に割り当てます',
         KS_variables_set:'%1 変数を %2 で設定',
         KS_variables_change:'%1 変数モード %2 を変更',
         KS_variables_value: '変数 %1',
         KS_variables_setString:'%1 文字列変数を %2 で設定',
         KS_global:'グローバル',
         KS_local:'ローカル',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: '長い',
         KS_MATH_FLOAT: '浮動小数点',
         KS_MATH_BOOLEAN: 'ブール値',
         KS_MATH_BYTE: 'バイト',
         KS_MATH_CHAR: '文字',
         KS_MATH_STRING: '文字列',
         KS_MATH_UNSIGNED_INT: '符号なし整数',
         KS_MATH_WORD: '単語',
         KS_MATH_UNSIGNED_LONG: '符号なしロング',
         KS_MATH_UNSIGNED_CHAR: '符号なし文字',
         KS_MATH_DOUBLE: '倍精度',

         KS_TEXT_LABEL:'テキスト',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'ロジック',
         KS_judge:'%1 %2 %3',
         KS_TIME_LABEL:'タイマー',
         KS_MILLIS: '実行時間 (ミリ秒)',
         KS_MICROS: '実行時間 (マイクロ秒)',

         ROBOT_CATEGORY: 'ライド',
         ROBOT_FORWARD: 'ロボット前進 左モーター%1 右モーター%2',
         ROBOT_BACK: 'ロボット後退 左モーター%1 右モーター%2',
         ROBOT_LEFT: 'ロボット左折 左モーター%1 右モーター%2',
         ROBOT_RIGHT: 'ロボット右折 左モーター%1 右モーター%2',
         ROBOT_STOP: 'ロボットストップ',
         MOTOR130_CATEGORY: 'モーター',
         MOTOR130_DIGITAL: 'モーター INA#%1 状態%2 INB#%3 状態%4',
         MOTOR130_ANALOG: 'モーター INA#%1 状態%2 INB#%3 アナログ書き込み%4',
         HC_SR04_CATEGORY: '超音波',
         HC_SR04_READ_DISTANCE: 'HC-SR04 トリガー ピン %1 エコー ピン %2 読み取り距離 %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
         KS_variables_declare:'%1 변수 유형 %2 이름 %3 선언 %4에 할당됨',
         KS_variables_set:'%1 변수를 %2로 설정',
         KS_variables_change:'%1 변수 모드 %2 변경',
         KS_variables_value: '변수 %1',
         KS_variables_setString:'%1 문자열 변수를 %2로 설정',
         KS_global:'글로벌',
         KS_local:'로컬',
         KS_MATH_INT: '정수',
         KS_MATH_LONG: '긴',
         KS_MATH_FLOAT: '부동',
         KS_MATH_BOOLEAN: '부울',
         KS_MATH_BYTE: '바이트',
         KS_MATH_CHAR: '문자',
         KS_MATH_STRING: '문자열',
         KS_MATH_UNSIGNED_INT: '부호 없는 정수',
         KS_MATH_WORD: '단어',
         KS_MATH_UNSIGNED_LONG: '부호 없는 롱',
         KS_MATH_UNSIGNED_CHAR: '부호 없는 문자',
         KS_MATH_DOUBLE: '더블',

         KS_TEXT_LABEL:'텍스트',
         KS_char: '문자%1',
         KS_string: '문자열%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'논리',
         KS_judge:'%1 %2 %3',
         KS_TIME_LABEL:'타이머',
         KS_MILLIS: '실행 시간 (밀리초)',
         KS_MICROS: '실행 시간 (마이크로초)',

         ROBOT_CATEGORY: '라이드',
         ROBOT_FORWARD: '로봇 전진 왼쪽 모터%1 오른쪽 모터%2',
         ROBOT_BACK: '로봇 후진 왼쪽 모터%1 오른쪽 모터%2',
         ROBOT_LEFT: '로봇 좌회전 왼쪽 모터%1 오른쪽 모터%2',
         ROBOT_RIGHT: '로봇 우회전 왼쪽 모터%1 오른쪽 모터%2',
         ROBOT_STOP: '로봇 중지',
         MOTOR130_CATEGORY: '모터',
         MOTOR130_DIGITAL: '모터 INA#%1 상태%2 INB#%3 상태%4',
         MOTOR130_ANALOG: '모터 INA#%1 상태%2 INB#%3 analogWrite%4',
         HC_SR04_CATEGORY: '초음파',
         HC_SR04_READ_DISTANCE: 'HC-SR04 트리거 핀 %1 에코 핀 %2 읽기 거리 %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaracja %1 zmiennej Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw zmienną %1 na %2',
        KS_variables_change:'Zmień tryb zmiennej %1 %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw zmienną łańcuchową %1 o %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'długi',
        KS_MATH_FLOAT: 'pływa',
        KS_MATH_BOOLEAN: 'wartość logiczna',
        KS_MATH_BYTE: 'bajt',
        KS_MATH_CHAR: 'znak',
        KS_MATH_STRING: 'ciąg znaków',
        KS_MATH_UNSIGNED_INT: 'bez znaku int',
        KS_MATH_WORD: 'słowo',
        KS_MATH_UNSIGNED_LONG: 'długi bez znaku',
        KS_MATH_UNSIGNED_CHAR: 'znak bez znaku',
        KS_MATH_DOUBLE: 'podwójne',

        KS_TEXT_LABEL:'TEKST',
        KS_char: 'znak%1',
        KS_string: 'ciąg%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1%2%3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'Czas działania (milisekundy)',
        KS_MICROS: 'Czas działania (mikrosekundy)',

        ROBOT_CATEGORY: 'Jazda',
        ROBOT_FORWARD: 'Robot do przodu lewy silnik%1 prawy silnik%2',
        ROBOT_BACK: 'Robot do tyłu lewy silnik%1 prawy silnik%2',
        ROBOT_LEFT: 'Robot skręca w lewo lewy silnik%1 prawy silnik%2',
        ROBOT_RIGHT: 'Robot skręca w prawo lewy silnik%1 prawy silnik%2',
        ROBOT_STOP: 'Zatrzymanie robota',
        MOTOR130_CATEGORY: 'Silnik',
        MOTOR130_DIGITAL: 'Silnik INA#%1 Stan%2 INB#%3 Stan%4',
        MOTOR130_ANALOG: 'Silnik INA#%1 Stan%2 INB#%3 analogWrite%4',
        HC_SR04_CATEGORY: 'Ultradźwięki',
        HC_SR04_READ_DISTANCE: 'HC-SR04 pin wyzwalający %1 pin echa %2 odległość odczytu %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de variável',
         KS_variables_declare:'Declare %1 variável Tipo %2 Nome %3 Atribuído a %4',
         KS_variables_set:'Definir %1 variável por %2',
         KS_variables_change:'Alterar %1 modo de variável %2',
         KS_variables_value: 'variável %1',
         KS_variables_setString:'Definir variável de string %1 por %2',
         KS_global:'Global',
         KS_local:'Local',
         KS_MATH_INT: 'int',
         KS_MATH_LONG: 'longo',
         KS_MATH_FLOAT: 'flutuar',
         KS_MATH_BOOLEAN: 'booleano',
         KS_MATH_BYTE: 'byte',
         KS_MATH_CHAR: 'char',
         KS_MATH_STRING: 'string',
         KS_MATH_UNSIGNED_INT: 'int unsigned',
         KS_MATH_WORD: 'palavra',
         KS_MATH_UNSIGNED_LONG: 'não assinado longo',
         KS_MATH_UNSIGNED_CHAR: 'caractere não assinado',
         KS_MATH_DOUBLE: 'duplo',

         KS_TEXT_LABEL:'TEXT',
         KS_char: 'char%1',
         KS_string: 'string%1',
         KS_data: '%1',

         KS_LOGIC_LABEL:'lógica',
         KS_judge:'%1 %2 %3',
         KS_TIME_LABEL:'Temporizador',
         KS_MILLIS: 'Tempo de execução (milissegundos)',
         KS_MICROS: 'Tempo de execução (microssegundos)',

         ROBOT_CATEGORY: "Passeio",
         ROBOT_FORWARD: 'Robô avança motor esq%1 motor dir%2',
         ROBOT_BACK: 'Robô recua motor esq%1 motor dir%2',
         ROBOT_LEFT: 'Robô vira esquerda motor esq%1 motor dir%2',
         ROBOT_RIGHT: 'Robô vira direita motor esq%1 motor dir%2',
         ROBOT_STOP: 'Parada do robô',
         MOTOR130_CATEGORY: 'Motor',
         MOTOR130_DIGITAL: 'Motor INA#%1 Estado%2 INB#%3 Estado%4',
         MOTOR130_ANALOG: 'Motor INA#%1 Estado%2 INB#%3 analogWrite%4',
         HC_SR04_CATEGORY: 'Ultrassônico',
         HC_SR04_READ_DISTANCE: 'HC-SR04 pino de ativação %1 pino de eco %2 distância de leitura %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL: 'Тип переменной',
         KS_variables_declare:'Объявить переменную %1 Тип %2 Имя %3 Назначено %4',
         KS_variables_set:'Установить переменную %1 на %2',
         KS_variables_change:'Изменить режим переменной %1 %2',
         KS_variables_value: 'переменная %1',
         KS_variables_setString:'Установить %1 строковую переменную на %2',
         KS_global: 'Глобальный',
         KS_local: 'Местный',
         KS_MATH_INT: 'целое',
         KS_MATH_LONG: 'длинный',
         KS_MATH_FLOAT: 'плавающая',
         KS_MATH_BOOLEAN: 'логическое значение',
         KS_MATH_BYTE: 'байт',
         KS_MATH_CHAR: 'символ',
         KS_MATH_STRING: 'строка',
         KS_MATH_UNSIGNED_INT: 'целое число без знака',
         KS_MATH_WORD: 'слово',
         KS_MATH_UNSIGNED_LONG: 'длинное без знака',
         KS_MATH_UNSIGNED_CHAR: 'беззнаковый символ',
         KS_MATH_DOUBLE: 'двойной',

         KS_TEXT_LABEL:'ТЕКСТ',
         KS_char: 'символ%1',
         KS_string: 'строка%1',
         KS_data: '%1',

         KS_LOGIC_LABEL: 'логика',
         KS_judge:'%1 %2 %3',
         KS_TIME_LABEL:'Таймер',
         KS_MILLIS: 'Время работы (миллисекунды)',
         KS_MICROS: 'Время работы (микросекунды)',

         ROBOT_CATEGORY: 'Поездка',
         ROBOT_FORWARD: 'Робот вперёд левый мотор%1 правый мотор%2',
         ROBOT_BACK: 'Робот назад левый мотор%1 правый мотор%2',
         ROBOT_LEFT: 'Робот налево левый мотор%1 правый мотор%2',
         ROBOT_RIGHT: 'Робот направо левый мотор%1 правый мотор%2',
         ROBOT_STOP: 'Остановка робота',
         MOTOR130_CATEGORY: 'Двигатель',
         MOTOR130_DIGITAL: 'Двигатель INA#%1 Состояние%2 INB#%3 Состояние%4',
         MOTOR130_ANALOG: 'Motor INA#%1 State%2 INB#%3 AnalogWrite%4',
         HC_SR04_CATEGORY: 'Ультразвук',
         HC_SR04_READ_DISTANCE: 'HC-SR04 триггерный вывод %1 эхо-вывод %2 расстояние чтения %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'計時器',
        KS_MILLIS: '運行時間 (毫秒)',
        KS_MICROS: '運行時間 (微秒)',
        ROBOT_CATEGORY: '運動',
        ROBOT_FORWARD: '小車前進 左電機速度為%1 右電機速度為%2',
        ROBOT_BACK: '小車後退 左電機速度為%1 右電機速度為%2',
        ROBOT_LEFT: '小車左轉 左電機速度為%1 右電機速度為%2',
        ROBOT_RIGHT: '小車右轉 左電機速度為%1 右電機速度為%2',
        ROBOT_STOP: '小車停',
        MOTOR130_CATEGORY: '電機',
        MOTOR130_DIGITAL: '電機驅動 INA#%1 電平為%2 INB#%3 電平為%4',
        MOTOR130_ANALOG: '電機驅動 INA#%1 電平為%2 INB#%3 模擬輸出值%4',
        HC_SR04_CATEGORY: '超聲波',
        HC_SR04_READ_DISTANCE: '超聲波傳感器 trig 引腳 %1 echo 引腳 %2 讀取距離 %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'计时器',
        KS_MILLIS: '运行时间 (毫秒)',
        KS_MICROS: '运行时间 (微秒)',
        ROBOT_CATEGORY: '运动',
        ROBOT_FORWARD: '小车前进 左电机速度为%1 右电机速度为%2',
        ROBOT_BACK: '小车后退 左电机速度为%1 右电机速度为%2',
        ROBOT_LEFT: '小车左转 左电机速度为%1 右电机速度为%2',
        ROBOT_RIGHT: '小车右转 左电机速度为%1 右电机速度为%2',
        ROBOT_STOP: '小车停止',
        MOTOR130_CATEGORY: '电机',
        MOTOR130_DIGITAL: '电机驱动 INA#%1 电平为%2 INB#%3 电平为%4',
        MOTOR130_ANALOG: '电机驱动 INA#%1 电平为%2 INB#%3 模拟输出值%4',
        HC_SR04_CATEGORY: '超声波',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['it'], {
        KS_VARIABLE_LABEL: 'Tipo di variabile',
        KS_variables_declare: 'Dichiara variabile numerica %1 Tipo %2 Nome %3 Valore %4',
        KS_variables_declare2: 'Dichiara variabile stringa %1 Tipo %2 Nome %3 Valore %4',
        KS_variables_set: 'Imposta variabile %1 a %2',
        KS_variables_change: 'Imposta variabile %1 modalità %2',
        KS_variables_value: 'Variabile %1',
        KS_variables_setString: 'Imposta variabile stringa %1 a %2',
        KS_global: 'Globale',
        KS_local: 'Locale',
        KS_MATH_INT: 'Intero',
        KS_MATH_LONG: 'Intero lungo',
        KS_MATH_FLOAT: 'Numero decimale',
        KS_MATH_BOOLEAN: 'Booleano',
        KS_MATH_BYTE: 'Byte',
        KS_MATH_CHAR: 'Carattere',
        KS_MATH_STRING: 'Stringa',
        KS_MATH_UNSIGNED_INT: 'Intero senza segno',
        KS_MATH_WORD: 'Parola',
        KS_MATH_UNSIGNED_LONG: 'Intero lungo senza segno',
        KS_MATH_UNSIGNED_CHAR: 'Carattere senza segno',
        KS_MATH_DOUBLE: 'Numero a doppia precisione',
        KS_TEXT_LABEL: 'TESTO',  
        KS_char: 'carattere%1',  
        KS_string: 'stringa%1',  
        KS_data: '%1', 
        KS_LOGIC_LABEL: 'Logica',
        KS_judge: '%1 %2 %3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'Tempo di esecuzione (millisecondi)',
        KS_MICROS: 'Tempo di esecuzione (microsecondi)',
        ROBOT_CATEGORY: 'Movimento',
        ROBOT_FORWARD: 'Auto avanti motore sx%1 motore dx%2',
        ROBOT_BACK: 'Auto indietro motore sx%1 motore dx%2',
        ROBOT_LEFT: 'Auto a sinistra motore sx%1 motore dx%2',
        ROBOT_RIGHT: 'Auto a destra motore sx%1 motore dx%2',
        ROBOT_STOP: 'Carro fermo',
        MOTOR130_CATEGORY: 'Motore',
        MOTOR130_DIGITAL: 'Motore attivo INA#%1 Livello %2 INB#%3 Livello %4',
        MOTOR130_ANALOG: 'Motore attivo INA#%1 Livello %2 INB#%3 Uscita analogica %4',
        HC_SR04_CATEGORY: 'Ultrasuoni',
        HC_SR04_READ_DISTANCE: 'Sensore a ultrasuoni trig Pin %1 echo Pin %2 Leggi distanza %3',
    });
    return Blockly;
}

exports = addMsg;
