/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 numeric variable Type %2 Name %3 Assigned to %4',
        KS_variables_declare2:'Declare %1 string variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable to %2',
        KS_variables_change:'Set %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 string variable to %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXT',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'runtime (ms)',
        KS_MICROS: 'runtime (us)',

        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Event',
        AIBOT_INIT_WIFI: 'Init AIbot WIFI configuration mode',
        AIBOT_INIT_MIC: 'I2S Microphone BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'I2S Speaker BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Backlight %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Start AIbot engine language %1 volume %2',
        AIBOT_LCD_SHOW_STATUS: 'LCD Screen Display %2 at %1',
        AIBOT_LOOP_STATE_CHANGE: 'When AIbot State is %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'When AIbot Receives Activation Info %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Received %1',
        AIBOT_LOOP_EMOTION: 'When AIbot Receives Emotion Message %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Received Emotion Code',
        AIBOT_EMOTION: 'Is Current Emotion %1?',
        AIBOT_EMOTION_LIST: 'Emotion Pack %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'When AIbot Receives Chat Message %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'Is Received Message Role %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Received Message Content',
        AIBOT_CONFIG_WEBSOCKET: 'Configure Backend: %1',
        AIBOT_LOOP_MCP: 'When AIbot Receives MCP Command %1 %2',

        AIBOT_WIFI_MANUAL: 'Direct WIFI Connection',
        AIBOT_WIFI_AUTO: 'Network Configuration Mode',
        AIBOT_BACKEND_XIAOZHI: 'Xiaozhi AI Backend',
        AIBOT_BACKEND_KEYES: 'Keyes AI Backend',
        AIBOT_STATE_IDLE: 'Idle',
        AIBOT_STATE_INITTED: 'Initted',
        AIBOT_STATE_LOADING: 'Loading',
        AIBOT_STATE_LOADING_FAILED: 'LoadingFailed',
        AIBOT_STATE_STANDBY: 'Standby',
        AIBOT_STATE_CONNECTING: 'Connecting',
        AIBOT_STATE_LISTENING: 'Listening',
        AIBOT_STATE_SPEAKING: 'Speaking',
        AIBOT_LCD_STATUS: 'Status Box',
        AIBOT_LCD_EMOTION: 'Emotion Box',
        AIBOT_LCD_CHAT: 'Content Box',
        AIBOT_ACTIVATION_CODE: 'Activation Code',
        AIBOT_ACTIVATION_MESSAGE: 'Activation URL',
        AIBOT_EMOTION_HAPPY: 'Happy',
        AIBOT_EMOTION_COOL: 'Cool',
        AIBOT_EMOTION_LAUGHING: 'Laughing',
        AIBOT_EMOTION_FUNNY: 'Funny',
        AIBOT_EMOTION_SAD: 'Sad',
        AIBOT_EMOTION_ANGRY: 'Angry',
        AIBOT_EMOTION_CRYING: 'Crying',
        AIBOT_EMOTION_LOVING: 'Loving',
        AIBOT_EMOTION_EMBARRASSED: 'Embarrassed',
        AIBOT_EMOTION_SURPRISED: 'Surprised',
        AIBOT_EMOTION_SHOCKED: 'Shocked',
        AIBOT_EMOTION_THINKING: 'Thinking',
        AIBOT_EMOTION_WINKING: 'Winking',
        AIBOT_EMOTION_RELAXED: 'Relaxed',
        AIBOT_EMOTION_DELICIOUS: 'Delicious',
        AIBOT_EMOTION_KISSY: 'Kissy',
        AIBOT_EMOTION_CONFIDENT: 'Confident',
        AIBOT_EMOTION_SLEEPY: 'Sleepy',
        AIBOT_EMOTION_SILLY: 'Silly',
        AIBOT_EMOTION_CONFUSED: 'Confused',
        AI_BOT_INIT_OLED: 'Initialize OLED Display SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'OLED Screen Show %2 at %1',
        AIBOT_WIFI_MODE_DIRECT: 'Direct WIFI Connection',
        AIBOT_WIFI_MODE_AUTO: 'Network Configuration Mode',
        AIBOT_OLED_STATUS_BOX: 'Status Box',
        AIBOT_OLED_EMOTION_BOX: 'Emotion Box',
        AIBOT_OLED_CONTENT_BOX: 'Content Box',
        AIBOT_ACTIVATION_URL: 'Activation URL',
        AIBOT_ROLE_ASSISTANT: 'Assistant',
        AIBOT_ROLE_USER: 'User'
    });
    Object.assign(Blockly.ScratchMsgs.locales['de'], {
        KS_VARIABLE_LABEL:'Variablentyp',
        KS_variables_declare:'Deklarieren %1 numerische Variable Typ %2 Name %3 Zugewiesen zu %4',
        KS_variables_declare2:'Deklarieren %1 String-Variable Typ %2 Name %3 Zugewiesen zu %4',
        KS_variables_set:'Setze %1 Variable auf %2',
        KS_variables_change:'Setze %1 Variable Modus %2',
        KS_variables_value: 'Variable %1',
        KS_variables_setString:'Setze %1 String-Variable auf %2',
        KS_global:'Global',
        KS_local:'Lokal',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXT',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'Logik',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'Laufzeit (ms)',
        KS_MICROS: 'Laufzeit (us)',

        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Ereignis',
        AIBOT_INIT_WIFI: 'Init AIbot WIFI-Konfigurationsmodus',
        AIBOT_INIT_MIC: 'I2S Mikrofon BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'I2S Lautsprecher BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Hintergrundbeleuchtung %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Starte die AIbot-Engine in Sprache %1 mit Lautstärke %2',
        AIBOT_LCD_SHOW_STATUS: 'LCD Bildschirm Anzeige %2 bei %1',
        AIBOT_LOOP_STATE_CHANGE: 'Wenn AIbot Status ist %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Wenn AIbot Aktivierungsinformationen erhält %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Empfangene %1',
        AIBOT_LOOP_EMOTION: 'Wenn AIbot Emotionsnachricht erhält %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Empfangener Emotionscode',
        AIBOT_EMOTION: 'Ist aktuelle Emotion %1?',
        AIBOT_EMOTION_LIST: 'Emotionspaket %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Wenn AIbot Chat-Nachricht erhält %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'Ist empfangene Nachrichtenrolle %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Empfangener Nachrichteninhalt',
        AIBOT_CONFIG_WEBSOCKET: 'Backend konfigurieren: %1',
        AIBOT_LOOP_MCP: 'Wenn AIbot MCP-Befehl erhält %1 %2',

        AIBOT_WIFI_MANUAL: 'Direkte WIFI-Verbindung',
        AIBOT_WIFI_AUTO: 'Netzwerkkonfigurationsmodus',
        AIBOT_BACKEND_XIAOZHI: 'Xiaozhi AI Backend',
        AIBOT_BACKEND_KEYES: 'Keyes AI Backend',
        AIBOT_STATE_IDLE: 'Leerlauf',
        AIBOT_STATE_INITTED: 'Initialisiert',
        AIBOT_STATE_LOADING: 'Lädt',
        AIBOT_STATE_LOADING_FAILED: 'Laden fehlgeschlagen',
        AIBOT_STATE_STANDBY: 'Bereitschaft',
        AIBOT_STATE_CONNECTING: 'Verbinden',
        AIBOT_STATE_LISTENING: 'Hören',
        AIBOT_STATE_SPEAKING: 'Sprechen',
        AIBOT_LCD_STATUS: 'Statusbox',
        AIBOT_LCD_EMOTION: 'Emotionsbox',
        AIBOT_LCD_CHAT: 'Inhaltsbox',
        AIBOT_ACTIVATION_CODE: 'Aktivierungscode',
        AIBOT_ACTIVATION_MESSAGE: 'Aktivierungs-URL',
        AIBOT_EMOTION_HAPPY: 'Glücklich',
        AIBOT_EMOTION_COOL: 'Cool',
        AIBOT_EMOTION_LAUGHING: 'Lachend',
        AIBOT_EMOTION_FUNNY: 'Lustig',
        AIBOT_EMOTION_SAD: 'Traurig',
        AIBOT_EMOTION_ANGRY: 'Wütend',
        AIBOT_EMOTION_CRYING: 'Weinend',
        AIBOT_EMOTION_LOVING: 'Liebevoll',
        AIBOT_EMOTION_EMBARRASSED: 'Verlegen',
        AIBOT_EMOTION_SURPRISED: 'Überrascht',
        AIBOT_EMOTION_SHOCKED: 'Schockiert',
        AIBOT_EMOTION_THINKING: 'Denkend',
        AIBOT_EMOTION_WINKING: 'Zwinkernd',
        AIBOT_EMOTION_RELAXED: 'Entspannt',
        AIBOT_EMOTION_DELICIOUS: 'Köstlich',
        AIBOT_EMOTION_KISSY: 'Küssend',
        AIBOT_EMOTION_CONFIDENT: 'Selbstbewusst',
        AIBOT_EMOTION_SLEEPY: 'Schläfrig',
        AIBOT_EMOTION_SILLY: 'Albern',
        AIBOT_EMOTION_CONFUSED: 'Verwirrt',
        AI_BOT_INIT_OLED: 'Initialisiere OLED Display SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'OLED Bildschirm Zeige %2 bei %1',
        AIBOT_WIFI_MODE_DIRECT: 'Direkte WIFI-Verbindung',
        AIBOT_WIFI_MODE_AUTO: 'Netzwerkkonfigurationsmodus',
        AIBOT_OLED_STATUS_BOX: 'Statusbox',
        AIBOT_OLED_EMOTION_BOX: 'Emotionsbox',
        AIBOT_OLED_CONTENT_BOX: 'Inhaltsbox',
        AIBOT_ACTIVATION_URL: 'Aktivierungs-URL',
        AIBOT_ROLE_ASSISTANT: 'Assistent',
        AIBOT_ROLE_USER: 'Benutzer'
    });
    Object.assign(Blockly.ScratchMsgs.locales['es'], {
        KS_VARIABLE_LABEL:'Tipo de variable',
        KS_variables_declare:'Declarar %1 variable numérica Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_declare2:'Declarar %1 variable de cadena Tipo %2 Nombre %3 Asignado a %4',
        KS_variables_set:'Establecer %1 variable en %2',
        KS_variables_change:'Establecer %1 modo variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Establecer %1 variable de cadena en %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXTO',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Temporizador',
        KS_MILLIS: 'tiempo de ejecución (ms)',
        KS_MICROS: 'tiempo de ejecución (us)',

        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Evento',
        AIBOT_INIT_WIFI: 'Init modo de configuración WIFI de AIbot',
        AIBOT_INIT_MIC: 'Micrófono I2S BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'Altavoz I2S BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Retroiluminación %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Iniciar motor de AIbot idioma %1 volumen %2',
        AIBOT_LCD_SHOW_STATUS: 'Pantalla LCD Mostrar %2 en %1',
        AIBOT_LOOP_STATE_CHANGE: 'Cuando Estado AIbot es %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Cuando AIbot Recibe Información de Activación %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Recibido %1',
        AIBOT_LOOP_EMOTION: 'Cuando AIbot Recibe Mensaje de Emoción %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Código de Emoción Recibido',
        AIBOT_EMOTION: '¿Es la Emoción Actual %1?',
        AIBOT_EMOTION_LIST: 'Paquete de Emociones %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Cuando AIbot Recibe Mensaje de Chat %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: '¿Es el Rol del Mensaje Recibido %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Contenido del Mensaje Recibido',
        AIBOT_CONFIG_WEBSOCKET: 'Configurar Backend: %1',
        AIBOT_LOOP_MCP: 'Cuando AIbot Recibe Comando MCP %1 %2',

        AIBOT_WIFI_MANUAL: 'Conexión WIFI Directa',
        AIBOT_WIFI_AUTO: 'Modo de Configuración de Red',
        AIBOT_BACKEND_XIAOZHI: 'Backend AI Xiaozhi',
        AIBOT_BACKEND_KEYES: 'Backend AI Keyes',
        AIBOT_STATE_IDLE: 'Inactivo',
        AIBOT_STATE_INITTED: 'Inicializado',
        AIBOT_STATE_LOADING: 'Cargando',
        AIBOT_STATE_LOADING_FAILED: 'Carga fallida',
        AIBOT_STATE_STANDBY: 'En Espera',
        AIBOT_STATE_CONNECTING: 'Conectando',
        AIBOT_STATE_LISTENING: 'Escuchando',
        AIBOT_STATE_SPEAKING: 'Hablando',
        AIBOT_LCD_STATUS: 'Caja de Estado',
        AIBOT_LCD_EMOTION: 'Caja de Emoción',
        AIBOT_LCD_CHAT: 'Caja de Contenido',
        AIBOT_ACTIVATION_CODE: 'Código de Activación',
        AIBOT_ACTIVATION_MESSAGE: 'URL de Activación',
        AIBOT_EMOTION_HAPPY: 'Feliz',
        AIBOT_EMOTION_COOL: 'Genial',
        AIBOT_EMOTION_LAUGHING: 'Riendo',
        AIBOT_EMOTION_FUNNY: 'Divertido',
        AIBOT_EMOTION_SAD: 'Triste',
        AIBOT_EMOTION_ANGRY: 'Enojado',
        AIBOT_EMOTION_CRYING: 'Llorando',
        AIBOT_EMOTION_LOVING: 'Amoroso',
        AIBOT_EMOTION_EMBARRASSED: 'Avergonzado',
        AIBOT_EMOTION_SURPRISED: 'Sorprendido',
        AIBOT_EMOTION_SHOCKED: 'Impactado',
        AIBOT_EMOTION_THINKING: 'Pensando',
        AIBOT_EMOTION_WINKING: 'Guiñando',
        AIBOT_EMOTION_RELAXED: 'Relajado',
        AIBOT_EMOTION_DELICIOUS: 'Delicioso',
        AIBOT_EMOTION_KISSY: 'Besando',
        AIBOT_EMOTION_CONFIDENT: 'Confiado',
        AIBOT_EMOTION_SLEEPY: 'Somnoliento',
        AIBOT_EMOTION_SILLY: 'Tonto',
        AIBOT_EMOTION_CONFUSED: 'Confundido',
        AI_BOT_INIT_OLED: 'Inicializar Pantalla OLED SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'Pantalla OLED Mostrar %2 en %1',
        AIBOT_WIFI_MODE_DIRECT: 'Conexión WIFI Directa',
        AIBOT_WIFI_MODE_AUTO: 'Modo de Configuración de Red',
        AIBOT_OLED_STATUS_BOX: 'Caja de Estado',
        AIBOT_OLED_EMOTION_BOX: 'Caja de Emoción',
        AIBOT_OLED_CONTENT_BOX: 'Caja de Contenido',
        AIBOT_ACTIVATION_URL: 'URL de Activación',
        AIBOT_ROLE_ASSISTANT: 'Asistente',
        AIBOT_ROLE_USER: 'Usuario'
    });
    Object.assign(Blockly.ScratchMsgs.locales['fr'], {
        KS_VARIABLE_LABEL:'Type de variable',
        KS_variables_declare:'Déclarer %1 variable numérique Type %2 Nom %3 Assigné à %4',
        KS_variables_declare2:'Déclarer %1 variable de chaîne Type %2 Nom %3 Assigné à %4',
        KS_variables_set:'Définir %1 variable sur %2',
        KS_variables_change:'Définir %1 mode variable %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Définir %1 variable de chaîne sur %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXTE',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'logique',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Minuteur',
        KS_MILLIS: 'temps d\'exécution (ms)',
        KS_MICROS: 'temps d\'exécution (us)',

        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Événement',
        AIBOT_INIT_WIFI: 'Init mode de configuration WIFI de l\'AIbot',
        AIBOT_INIT_MIC: 'Microphone I2S BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'Haut-parleur I2S BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Rétroéclairage %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Démarrer le moteur AIbot langue %1 volume %2',
        AIBOT_LCD_SHOW_STATUS: 'Écran LCD Afficher %2 à %1',
        AIBOT_LOOP_STATE_CHANGE: 'Quand État AIbot est %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Quand AIbot Reçoit Informations d\'Activation %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Reçu %1',
        AIBOT_LOOP_EMOTION: 'Quand AIbot Reçoit Message d\'Émotion %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Code d\'Émotion Reçu',
        AIBOT_EMOTION: 'L\'Émotion Actuelle est-elle %1 ?',
        AIBOT_EMOTION_LIST: 'Paquet d\'Émotions %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Quand AIbot Reçoit Message de Chat %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'Le Rôle du Message Reçu est-il %1 ?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Contenu du Message Reçu',
        AIBOT_CONFIG_WEBSOCKET: 'Configurer Backend: %1',
        AIBOT_LOOP_MCP: 'Quand AIbot Reçoit Commande MCP %1 %2',

        AIBOT_WIFI_MANUAL: 'Connexion WIFI Directe',
        AIBOT_WIFI_AUTO: 'Mode de Configuration Réseau',
        AIBOT_BACKEND_XIAOZHI: 'Backend AI Xiaozhi',
        AIBOT_BACKEND_KEYES: 'Backend AI Keyes',
        AIBOT_STATE_IDLE: 'Inactif',
        AIBOT_STATE_INITTED: 'Initialisé',
        AIBOT_STATE_LOADING: 'Chargement',
        AIBOT_STATE_LOADING_FAILED: 'Échec du chargement',
        AIBOT_STATE_STANDBY: 'En Attente',
        AIBOT_STATE_CONNECTING: 'Connexion',
        AIBOT_STATE_LISTENING: 'Écoute',
        AIBOT_STATE_SPEAKING: 'Parlant',
        AIBOT_LCD_STATUS: 'Boîte de Statut',
        AIBOT_LCD_EMOTION: 'Boîte d\'Émotion',
        AIBOT_LCD_CHAT: 'Boîte de Contenu',
        AIBOT_ACTIVATION_CODE: 'Code d\'Activation',
        AIBOT_ACTIVATION_MESSAGE: 'URL d\'Activation',
        AIBOT_EMOTION_HAPPY: 'Heureux',
        AIBOT_EMOTION_COOL: 'Cool',
        AIBOT_EMOTION_LAUGHING: 'Riant',
        AIBOT_EMOTION_FUNNY: 'Drôle',
        AIBOT_EMOTION_SAD: 'Triste',
        AIBOT_EMOTION_ANGRY: 'En Colère',
        AIBOT_EMOTION_CRYING: 'Pleurant',
        AIBOT_EMOTION_LOVING: 'Aimant',
        AIBOT_EMOTION_EMBARRASSED: 'Embarrassé',
        AIBOT_EMOTION_SURPRISED: 'Surpris',
        AIBOT_EMOTION_SHOCKED: 'Choqué',
        AIBOT_EMOTION_THINKING: 'Pensant',
        AIBOT_EMOTION_WINKING: 'Clignant de l\'œil',
        AIBOT_EMOTION_RELAXED: 'Détendu',
        AIBOT_EMOTION_DELICIOUS: 'Délicieux',
        AIBOT_EMOTION_KISSY: 'Embrassant',
        AIBOT_EMOTION_CONFIDENT: 'Confident',
        AIBOT_EMOTION_SLEEPY: 'Somnolent',
        AIBOT_EMOTION_SILLY: 'Bête',
        AIBOT_EMOTION_CONFUSED: 'Confus',
        AI_BOT_INIT_OLED: 'Initialiser Écran OLED SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'Écran OLED Afficher %2 à %1',
        AIBOT_WIFI_MODE_DIRECT: 'Connexion WIFI Directe',
        AIBOT_WIFI_MODE_AUTO: 'Mode de Configuration Réseau',
        AIBOT_OLED_STATUS_BOX: 'Boîte de Statut',
        AIBOT_OLED_EMOTION_BOX: 'Boîte d\'Émotion',
        AIBOT_OLED_CONTENT_BOX: 'Boîte de Contenu',
        AIBOT_ACTIVATION_URL: 'URL d\'Activation',
        AIBOT_ROLE_ASSISTANT: 'Assistant',
        AIBOT_ROLE_USER: 'Utilisateur'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ja'], {
        KS_VARIABLE_LABEL:'変数の種類',
        KS_variables_declare:'%1 数値変数 型 %2 名前 %3 割り当て %4',
        KS_variables_declare2:'%1 文字列変数 型 %2 名前 %3 割り当て %4',
        KS_variables_set:'%1 変数を %2 に設定',
        KS_variables_change:'%1 変数モード %2 を設定',
        KS_variables_value: '変数 %1',
        KS_variables_setString:'%1 文字列変数を %2 に設定',
        KS_global:'グローバル',
        KS_local:'ローカル',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'テキスト',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'論理',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'タイマー',
        KS_MILLIS: '実行時間 (ms)',
        KS_MICROS: '実行時間 (us)',

        AIBOT_CATEGORY_INIT: '初期化',
        AIBOT_CATEGORY_EVENT: 'イベント',
        AIBOT_INIT_WIFI: 'Init AIbot WIFI設定モード',
        AIBOT_INIT_MIC: 'I2S マイク BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'I2S スピーカー BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD バックライト %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'AIbotエンジンを起動 言語%1 音量%2',
        AIBOT_LCD_SHOW_STATUS: 'LCD 画面 %1 で %2 を表示',
        AIBOT_LOOP_STATE_CHANGE: 'AIbot 状態が %1 のとき %2 %3',
        AIBOT_LOOP_ACTIVATION: 'AIbot がアクティベーション情報を受信したとき %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: '受信した %1',
        AIBOT_LOOP_EMOTION: 'AIbot が感情メッセージを受信したとき %1 %2',
        GET_AIBOT_EMOTION_RESULT: '受信した感情コード',
        AIBOT_EMOTION: '現在の感情は %1 か？',
        AIBOT_EMOTION_LIST: '感情パック %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'AIbot がチャットメッセージを受信したとき %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: '受信したメッセージの役割は %1 か？',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: '受信したメッセージ内容',
        AIBOT_CONFIG_WEBSOCKET: 'バックエンドを設定: %1',
        AIBOT_LOOP_MCP: 'AIbot が MCP コマンドを受信したとき %1 %2',

        AIBOT_WIFI_MANUAL: 'WIFI 直接接続',
        AIBOT_WIFI_AUTO: 'ネットワーク構成モード',
        AIBOT_BACKEND_XIAOZHI: 'Xiaozhi AI バックエンド',
        AIBOT_BACKEND_KEYES: 'Keyes AI バックエンド',
        AIBOT_STATE_IDLE: 'アイドル',
        AIBOT_STATE_INITTED: '初期化済み',
        AIBOT_STATE_LOADING: '読み込み中',
        AIBOT_STATE_LOADING_FAILED: '読み込み失敗',
        AIBOT_STATE_STANDBY: 'スタンバイ',
        AIBOT_STATE_CONNECTING: '接続中',
        AIBOT_STATE_LISTENING: '聴取中',
        AIBOT_STATE_SPEAKING: '話中',
        AIBOT_LCD_STATUS: 'ステータスボックス',
        AIBOT_LCD_EMOTION: '感情ボックス',
        AIBOT_LCD_CHAT: 'コンテンツボックス',
        AIBOT_ACTIVATION_CODE: 'アクティベーションコード',
        AIBOT_ACTIVATION_MESSAGE: 'アクティベーション URL',
        AIBOT_EMOTION_HAPPY: '幸せ',
        AIBOT_EMOTION_COOL: 'クール',
        AIBOT_EMOTION_LAUGHING: '笑う',
        AIBOT_EMOTION_FUNNY: '面白い',
        AIBOT_EMOTION_SAD: '悲しい',
        AIBOT_EMOTION_ANGRY: '怒っている',
        AIBOT_EMOTION_CRYING: '泣いている',
        AIBOT_EMOTION_LOVING: '愛情深い',
        AIBOT_EMOTION_EMBARRASSED: '恥ずかしい',
        AIBOT_EMOTION_SURPRISED: '驚いた',
        AIBOT_EMOTION_SHOCKED: 'ショックを受けた',
        AIBOT_EMOTION_THINKING: '考えている',
        AIBOT_EMOTION_WINKING: 'ウィンク',
        AIBOT_EMOTION_RELAXED: 'リラックスした',
        AIBOT_EMOTION_DELICIOUS: 'おいしい',
        AIBOT_EMOTION_KISSY: 'キス',
        AIBOT_EMOTION_CONFIDENT: '自信がある',
        AIBOT_EMOTION_SLEEPY: '眠い',
        AIBOT_EMOTION_SILLY: 'ばかげた',
        AIBOT_EMOTION_CONFUSED: '混乱した',
        AI_BOT_INIT_OLED: 'OLED ディスプレイを初期化 SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'OLED 画面で %1 に %2 を表示',
        AIBOT_WIFI_MODE_DIRECT: 'WIFI 直接接続',
        AIBOT_WIFI_MODE_AUTO: 'ネットワーク構成モード',
        AIBOT_OLED_STATUS_BOX: 'ステータスボックス',
        AIBOT_OLED_EMOTION_BOX: '感情ボックス',
        AIBOT_OLED_CONTENT_BOX: 'コンテンツボックス',
        AIBOT_ACTIVATION_URL: 'アクティベーションURL',
        AIBOT_ROLE_ASSISTANT: 'アシスタント',
        AIBOT_ROLE_USER: 'ユーザー'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
        KS_VARIABLE_LABEL:'변수 유형',
        KS_variables_declare:'%1 숫자 변수 선언 유형 %2 이름 %3 할당 %4',
        KS_variables_declare2:'%1 문자열 변수 선언 유형 %2 이름 %3 할당 %4',
        KS_variables_set:'%1 변수를 %2로 설정',
        KS_variables_change:'%1 변수 모드 %2 설정',
        KS_variables_value: '변수 %1',
        KS_variables_setString:'%1 문자열 변수를 %2로 설정',
        KS_global:'전역',
        KS_local:'지역',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'텍스트',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'논리',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'타이머',
        KS_MILLIS: '실행 시간 (ms)',
        KS_MICROS: '실행 시간 (us)',

        AIBOT_CATEGORY_INIT: '초기화',
        AIBOT_CATEGORY_EVENT: '이벤트',
        AIBOT_INIT_WIFI: 'Init AIbot WIFI 구성 모드',
        AIBOT_INIT_MIC: 'I2S 마이크 BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'I2S 스피커 BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD 백라이트 %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'AIbot 엔진 시작 언어 %1 볼륨 %2',
        AIBOT_LCD_SHOW_STATUS: 'LCD 화면 %1에 %2 표시',
        AIBOT_LOOP_STATE_CHANGE: 'AIbot 상태가 %1 일 때 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'AIbot가 활성화 정보를 수신할 때 %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: '수신된 %1',
        AIBOT_LOOP_EMOTION: 'AIbot가 감정 메시지를 수신할 때 %1 %2',
        GET_AIBOT_EMOTION_RESULT: '수신된 감정 코드',
        AIBOT_EMOTION: '현재 감정은 %1인가?',
        AIBOT_EMOTION_LIST: '감정 팩 %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'AIbot가 채팅 메시지를 수신할 때 %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: '수신된 메시지 역할은 %1인가?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: '수신된 메시지 내용',
        AIBOT_CONFIG_WEBSOCKET: '백엔드 구성: %1',
        AIBOT_LOOP_MCP: 'AIbot가 MCP 명령을 수신할 때 %1 %2',

        AIBOT_WIFI_MANUAL: 'WIFI 직접 연결',
        AIBOT_WIFI_AUTO: '네트워크 구성 모드',
        AIBOT_BACKEND_XIAOZHI: 'Xiaozhi AI 백엔드',
        AIBOT_BACKEND_KEYES: 'Keyes AI 백엔드',
        AIBOT_STATE_IDLE: '유휴',
        AIBOT_STATE_INITTED: '초기화됨',
        AIBOT_STATE_LOADING: '로딩 중',
        AIBOT_STATE_LOADING_FAILED: '로딩 실패',
        AIBOT_STATE_STANDBY: '대기',
        AIBOT_STATE_CONNECTING: '연결 중',
        AIBOT_STATE_LISTENING: '청취 중',
        AIBOT_STATE_SPEAKING: '말하는 중',
        AIBOT_LCD_STATUS: '상태 상자',
        AIBOT_LCD_EMOTION: '감정 상자',
        AIBOT_LCD_CHAT: '콘텐츠 상자',
        AIBOT_ACTIVATION_CODE: '활성화 코드',
        AIBOT_ACTIVATION_MESSAGE: '활성화 URL',
        AIBOT_EMOTION_HAPPY: '행복한',
        AIBOT_EMOTION_COOL: '멋진',
        AIBOT_EMOTION_LAUGHING: '웃는',
        AIBOT_EMOTION_FUNNY: '재미있는',
        AIBOT_EMOTION_SAD: '슬픈',
        AIBOT_EMOTION_ANGRY: '화난',
        AIBOT_EMOTION_CRYING: '우는',
        AIBOT_EMOTION_LOVING: '사랑스러운',
        AIBOT_EMOTION_EMBARRASSED: '당황한',
        AIBOT_EMOTION_SURPRISED: '놀란',
        AIBOT_EMOTION_SHOCKED: '충격받은',
        AIBOT_EMOTION_THINKING: '생각하는',
        AIBOT_EMOTION_WINKING: '윙크하는',
        AIBOT_EMOTION_RELAXED: '편안한',
        AIBOT_EMOTION_DELICIOUS: '맛있는',
        AIBOT_EMOTION_KISSY: '키스하는',
        AIBOT_EMOTION_CONFIDENT: '자신 있는',
        AIBOT_EMOTION_SLEEPY: '졸린',
        AIBOT_EMOTION_SILLY: '어리석은',
        AIBOT_EMOTION_CONFUSED: '혼란스러운',
        AI_BOT_INIT_OLED: 'OLED 디스플레이 초기화 SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'OLED 화면에서 %1에 %2 표시',
        AIBOT_WIFI_MODE_DIRECT: 'WIFI 직접 연결',
        AIBOT_WIFI_MODE_AUTO: '네트워크 구성 모드',
        AIBOT_OLED_STATUS_BOX: '상태 상자',
        AIBOT_OLED_EMOTION_BOX: '감정 상자',
        AIBOT_OLED_CONTENT_BOX: '콘텐츠 상자',
        AIBOT_ACTIVATION_URL: '활성화 URL',
        AIBOT_ROLE_ASSISTANT: '어시스턴트',
        AIBOT_ROLE_USER: '사용자'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pl'], {
        KS_VARIABLE_LABEL:'Typ zmiennej',
        KS_variables_declare:'Deklaruj %1 zmienną liczbową Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_declare2:'Deklaruj %1 zmienną łańcuchową Typ %2 Nazwa %3 Przypisana do %4',
        KS_variables_set:'Ustaw %1 zmienną na %2',
        KS_variables_change:'Ustaw %1 tryb zmiennej %2',
        KS_variables_value: 'zmienna %1',
        KS_variables_setString:'Ustaw %1 zmienną łańcuchową na %2',
        KS_global:'Globalny',
        KS_local:'Lokalny',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEKST',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'logika',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Timer',
        KS_MILLIS: 'czas wykonywania (ms)',
        KS_MICROS: 'czas wykonywania (us)',

        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Wydarzenie',
        AIBOT_INIT_WIFI: 'Init tryb konfiguracji WIFI AIbot',
        AIBOT_INIT_MIC: 'Mikrofon I2S BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'Głośnik I2S BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Podświetlenie %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Uruchom silnik AIbot, język %1, głośność %2',
        AIBOT_LCD_SHOW_STATUS: 'Ekran LCD Wyświetl %2 w %1',
        AIBOT_LOOP_STATE_CHANGE: 'Gdy Stan AIbot to %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Gdy AIbot Otrzyma Informacje o Aktywacji %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Otrzymane %1',
        AIBOT_LOOP_EMOTION: 'Gdy AIbot Otrzyma Wiadomość Emocji %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Otrzymany Kod Emocji',
        AIBOT_EMOTION: 'Czy Aktualna Emocja to %1?',
        AIBOT_EMOTION_LIST: 'Pakiet Emocji %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Gdy AIbot Otrzyma Wiadomość Czatu %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'Czy Rola Otrzymanej Wiadomości to %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Treść Otrzymanej Wiadomości',
        AIBOT_CONFIG_WEBSOCKET: 'Konfiguruj Backend: %1',
        AIBOT_LOOP_MCP: 'Gdy AIbot Otrzyma Polecenie MCP %1 %2',

        AIBOT_WIFI_MANUAL: 'Bezpośrednie Połączenie WIFI',
        AIBOT_WIFI_AUTO: 'Tryb Konfiguracji Sieci',
        AIBOT_BACKEND_XIAOZHI: 'Backend AI Xiaozhi',
        AIBOT_BACKEND_KEYES: 'Backend AI Keyes',
        AIBOT_STATE_IDLE: 'Bezczynny',
        AIBOT_STATE_INITTED: 'Zainicjowany',
        AIBOT_STATE_LOADING: 'Ładowanie',
        AIBOT_STATE_LOADING_FAILED: 'Ładowanie nieudane',
        AIBOT_STATE_STANDBY: 'W Trybie Oczekiwania',
        AIBOT_STATE_CONNECTING: 'Łączenie',
        AIBOT_STATE_LISTENING: 'Słuchanie',
        AIBOT_STATE_SPEAKING: 'Mówienie',
        AIBOT_LCD_STATUS: 'Pole Statusu',
        AIBOT_LCD_EMOTION: 'Pole Emocji',
        AIBOT_LCD_CHAT: 'Pole Treści',
        AIBOT_ACTIVATION_CODE: 'Kod Aktywacji',
        AIBOT_ACTIVATION_MESSAGE: 'URL Aktywacji',
        AIBOT_EMOTION_HAPPY: 'Szczęśliwy',
        AIBOT_EMOTION_COOL: 'Fajny',
        AIBOT_EMOTION_LAUGHING: 'Śmiejący się',
        AIBOT_EMOTION_FUNNY: 'Zabawny',
        AIBOT_EMOTION_SAD: 'Smutny',
        AIBOT_EMOTION_ANGRY: 'Zły',
        AIBOT_EMOTION_CRYING: 'Płaczący',
        AIBOT_EMOTION_LOVING: 'Kochający',
        AIBOT_EMOTION_EMBARRASSED: 'Zakłopotany',
        AIBOT_EMOTION_SURPRISED: 'Zaskoczony',
        AIBOT_EMOTION_SHOCKED: 'Zszokowany',
        AIBOT_EMOTION_THINKING: 'Myślący',
        AIBOT_EMOTION_WINKING: 'Mrugający',
        AIBOT_EMOTION_RELAXED: 'Zrelaksowany',
        AIBOT_EMOTION_DELICIOUS: 'Pyszny',
        AIBOT_EMOTION_KISSY: 'Całujący',
        AIBOT_EMOTION_CONFIDENT: 'Pewny siebie',
        AIBOT_EMOTION_SLEEPY: 'Śpiący',
        AIBOT_EMOTION_SILLY: 'Głupi',
        AIBOT_EMOTION_CONFUSED: 'Zdezorientowany',
        AI_BOT_INIT_OLED: 'Inicjalizuj Wyświetlacz OLED SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'Ekran OLED Pokaż %2 w %1',
        AIBOT_WIFI_MODE_DIRECT: 'Bezpośrednie Połączenie WIFI',
        AIBOT_WIFI_MODE_AUTO: 'Tryb Konfiguracji Sieci',
        AIBOT_OLED_STATUS_BOX: 'Pole Statusu',
        AIBOT_OLED_EMOTION_BOX: 'Pole Emocji',
        AIBOT_OLED_CONTENT_BOX: 'Pole Zawartości',
        AIBOT_ACTIVATION_URL: 'URL Aktywacji',
        AIBOT_ROLE_ASSISTANT: 'Asystent',
        AIBOT_ROLE_USER: 'Użytkownik'
    });
    Object.assign(Blockly.ScratchMsgs.locales['pt'], {
        KS_VARIABLE_LABEL:'Tipo de Variável',
        KS_variables_declare:'Declarar %1 variável numérica Tipo %2 Nome %3 Atribuído a %4',
        KS_variables_declare2:'Declarar %1 variável de string Tipo %2 Nome %3 Atribuído a %4',
        KS_variables_set:'Definir %1 variável para %2',
        KS_variables_change:'Definir %1 modo variável %2',
        KS_variables_value: 'variável %1',
        KS_variables_setString:'Definir %1 variável de string para %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'TEXTO',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'lógica',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Temporizador',
        KS_MILLIS: 'tempo de execução (ms)',
        KS_MICROS: 'tempo de execução (us)',

        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Evento',
        AIBOT_INIT_WIFI: 'Init modo de configuração WIFI do AIbot',
        AIBOT_INIT_MIC: 'Microfone I2S BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'Alto-falante I2S BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Retroiluminação %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Iniciar motor AIbot idioma %1 volume %2',
        AIBOT_LCD_SHOW_STATUS: 'Tela LCD Exibir %2 em %1',
        AIBOT_LOOP_STATE_CHANGE: 'Quando Estado AIbot for %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Quando AIbot Receber Informações de Ativação %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Recebido %1',
        AIBOT_LOOP_EMOTION: 'Quando AIbot Receber Mensagem de Emoção %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Código de Emoção Recebido',
        AIBOT_EMOTION: 'A Emoção Atual é %1?',
        AIBOT_EMOTION_LIST: 'Pacote de Emoções %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Quando AIbot Receber Mensagem de Chat %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'O Papel da Mensagem Recebida é %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Conteúdo da Mensagem Recebida',
        AIBOT_CONFIG_WEBSOCKET: 'Configurar Backend: %1',
        AIBOT_LOOP_MCP: 'Quando AIbot Receber Comando MCP %1 %2',

        AIBOT_WIFI_MANUAL: 'Conexão WIFI Direta',
        AIBOT_WIFI_AUTO: 'Modo de Configuração de Rede',
        AIBOT_BACKEND_XIAOZHI: 'Backend AI Xiaozhi',
        AIBOT_BACKEND_KEYES: 'Backend AI Keyes',
        AIBOT_STATE_IDLE: 'Ocioso',
        AIBOT_STATE_INITTED: 'Inicializado',
        AIBOT_STATE_LOADING: 'Carregando',
        AIBOT_STATE_LOADING_FAILED: 'Falha no carregamento',
        AIBOT_STATE_STANDBY: 'Em Espera',
        AIBOT_STATE_CONNECTING: 'Conectando',
        AIBOT_STATE_LISTENING: 'Ouvindo',
        AIBOT_STATE_SPEAKING: 'Falando',
        AIBOT_LCD_STATUS: 'Caixa de Status',
        AIBOT_LCD_EMOTION: 'Caixa de Emoção',
        AIBOT_LCD_CHAT: 'Caixa de Conteúdo',
        AIBOT_ACTIVATION_CODE: 'Código de Ativação',
        AIBOT_ACTIVATION_MESSAGE: 'URL de Ativação',
        AIBOT_EMOTION_HAPPY: 'Feliz',
        AIBOT_EMOTION_COOL: 'Legal',
        AIBOT_EMOTION_LAUGHING: 'Rindo',
        AIBOT_EMOTION_FUNNY: 'Engraçado',
        AIBOT_EMOTION_SAD: 'Triste',
        AIBOT_EMOTION_ANGRY: 'Irritado',
        AIBOT_EMOTION_CRYING: 'Chorando',
        AIBOT_EMOTION_LOVING: 'Amoroso',
        AIBOT_EMOTION_EMBARRASSED: 'Envergonhado',
        AIBOT_EMOTION_SURPRISED: 'Surpreso',
        AIBOT_EMOTION_SHOCKED: 'Chocado',
        AIBOT_EMOTION_THINKING: 'Pensando',
        AIBOT_EMOTION_WINKING: 'Piscando',
        AIBOT_EMOTION_RELAXED: 'Relaxado',
        AIBOT_EMOTION_DELICIOUS: 'Delicioso',
        AIBOT_EMOTION_KISSY: 'Beijando',
        AIBOT_EMOTION_CONFIDENT: 'Confiante',
        AIBOT_EMOTION_SLEEPY: 'Sonolento',
        AIBOT_EMOTION_SILLY: 'Tolo',
        AIBOT_EMOTION_CONFUSED: 'Confuso',
        AI_BOT_INIT_OLED: 'Inicializar Display OLED SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'Tela OLED Mostrar %2 em %1',
        AIBOT_WIFI_MODE_DIRECT: 'Conexão WIFI Direta',
        AIBOT_WIFI_MODE_AUTO: 'Modo de Configuração de Rede',
        AIBOT_OLED_STATUS_BOX: 'Caixa de Status',
        AIBOT_OLED_EMOTION_BOX: 'Caixa de Emoção',
        AIBOT_OLED_CONTENT_BOX: 'Caixa de Conteúdo',
        AIBOT_ACTIVATION_URL: 'URL de Ativação',
        AIBOT_ROLE_ASSISTANT: 'Assistente',
        AIBOT_ROLE_USER: 'Usuário'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ru'], {
        KS_VARIABLE_LABEL:'Тип переменной',
        KS_variables_declare:'Объявить %1 числовую переменную Тип %2 Имя %3 Присвоено %4',
        KS_variables_declare2:'Объявить %1 строковую переменную Тип %2 Имя %3 Присвоено %4',
        KS_variables_set:'Установить %1 переменную на %2',
        KS_variables_change:'Установить %1 режим переменной %2',
        KS_variables_value: 'переменная %1',
        KS_variables_setString:'Установить %1 строковую переменную на %2',
        KS_global:'Глобальный',
        KS_local:'Локальный',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL:'ТЕКСТ',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'логика',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'Таймер',
        KS_MILLIS: 'время выполнения (мс)',
        KS_MICROS: 'время выполнения (мкс)',

        AIBOT_CATEGORY_INIT: 'Инициализация',
        AIBOT_CATEGORY_EVENT: 'Событие',
        AIBOT_INIT_WIFI: 'Init режим настройки WIFI для AIbot',
        AIBOT_INIT_MIC: 'Микрофон I2S BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'Динамик I2S BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Подсветка %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Запустить движок AIbot, язык %1, громкость %2',
        AIBOT_LCD_SHOW_STATUS: 'Экран LCD Отобразить %2 в %1',
        AIBOT_LOOP_STATE_CHANGE: 'Когда Состояние AIbot %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Когда AIbot Получит Информацию об Активации %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Получено %1',
        AIBOT_LOOP_EMOTION: 'Когда AIbot Получит Сообщение об Эмоции %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Полученный Код Эмоции',
        AIBOT_EMOTION: 'Текущая Эмоция %1?',
        AIBOT_EMOTION_LIST: 'Пакет Эмоций %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Когда AIbot Получит Сообщение Чата %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'Роль Полученного Сообщения %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Содержимое Полученного Сообщения',
        AIBOT_CONFIG_WEBSOCKET: 'Настроить Backend: %1',
        AIBOT_LOOP_MCP: 'Когда AIbot Получит Команду MCP %1 %2',

        AIBOT_WIFI_MANUAL: 'Прямое WIFI-СОЕДИНЕНИЕ',
        AIBOT_WIFI_AUTO: 'Режим Настройки Сети',
        AIBOT_BACKEND_XIAOZHI: 'Backend AI Xiaozhi',
        AIBOT_BACKEND_KEYES: 'Backend AI Keyes',
        AIBOT_STATE_IDLE: 'Простой',
        AIBOT_STATE_INITTED: 'Инициализировано',
        AIBOT_STATE_LOADING: 'Загрузка',
        AIBOT_STATE_LOADING_FAILED: 'Ошибка загрузки',
        AIBOT_STATE_STANDBY: 'В Режиме Ожидания',
        AIBOT_STATE_CONNECTING: 'Подключение',
        AIBOT_STATE_LISTENING: 'Прослушивание',
        AIBOT_STATE_SPEAKING: 'Говорение',
        AIBOT_LCD_STATUS: 'Блок Статуса',
        AIBOT_LCD_EMOTION: 'Блок Эмоции',
        AIBOT_LCD_CHAT: 'Блок Содержимого',
        AIBOT_ACTIVATION_CODE: 'Код Активации',
        AIBOT_ACTIVATION_MESSAGE: 'URL Активации',
        AIBOT_EMOTION_HAPPY: 'Счастливый',
        AIBOT_EMOTION_COOL: 'Крутой',
        AIBOT_EMOTION_LAUGHING: 'Смеющийся',
        AIBOT_EMOTION_FUNNY: 'Смешной',
        AIBOT_EMOTION_SAD: 'Грустный',
        AIBOT_EMOTION_ANGRY: 'Злой',
        AIBOT_EMOTION_CRYING: 'Плачущий',
        AIBOT_EMOTION_LOVING: 'Любящий',
        AIBOT_EMOTION_EMBARRASSED: 'Смущенный',
        AIBOT_EMOTION_SURPRISED: 'Удивленный',
        AIBOT_EMOTION_SHOCKED: 'Шокированный',
        AIBOT_EMOTION_THINKING: 'Думающий',
        AIBOT_EMOTION_WINKING: 'Подмигивающий',
        AIBOT_EMOTION_RELAXED: 'Расслабленный',
        AIBOT_EMOTION_DELICIOUS: 'Вкусный',
        AIBOT_EMOTION_KISSY: 'Целующий',
        AIBOT_EMOTION_CONFIDENT: 'Уверенный',
        AIBOT_EMOTION_SLEEPY: 'Сонный',
        AIBOT_EMOTION_SILLY: 'Глупый',
        AIBOT_EMOTION_CONFUSED: 'Запутанный',
        AI_BOT_INIT_OLED: 'Инициализировать Дисплей OLED SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'Экран OLED Показать %2 в %1',
        AIBOT_WIFI_MODE_DIRECT: 'Прямое Соединение WIFI',
        AIBOT_WIFI_MODE_AUTO: 'Режим Конфигурации Сети',
        AIBOT_OLED_STATUS_BOX: 'Бокс Статуса',
        AIBOT_OLED_EMOTION_BOX: 'Бокс Эмоции',
        AIBOT_OLED_CONTENT_BOX: 'Бокс Содержимого',
        AIBOT_ACTIVATION_URL: 'URL Активации',
        AIBOT_ROLE_ASSISTANT: 'Ассистент',
        AIBOT_ROLE_USER: 'Пользователь'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        KS_VARIABLE_LABEL:'變量類型',
        KS_variables_declare:'聲明 %1 數字變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_declare2:'聲明 %1 字符串變量 類型 %2 名稱 %3 賦值為 %4',
        KS_variables_set:'設置 %1 變量 為 %2',
        KS_variables_change:'設置 %1 變量 模式 %2',
        KS_variables_value: '變量 %1',
        KS_variables_setString:'設置 %1 字符串變量 為 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整數',
        KS_MATH_LONG: '長整數',
        KS_MATH_FLOAT: '小數',
        KS_MATH_BOOLEAN: '布爾',
        KS_MATH_BYTE: '字節',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '無符號整數',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '無符號長整數',
        KS_MATH_UNSIGNED_CHAR: '無符號字符',
        KS_MATH_DOUBLE: '雙精度浮點數',
        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'邏輯',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'計時器',
        KS_MILLIS: '運行時間 (毫秒)',
        KS_MICROS: '運行時間 (微秒)',

        AIBOT_CATEGORY_INIT: '初始化',
        AIBOT_CATEGORY_EVENT: '事件',
        AIBOT_INIT_WIFI: '初始化 AIbot WIFI配網模式',
        AIBOT_INIT_MIC: 'I2S 麥克風 BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'I2S 揚聲器 BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD 背光 %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: '啟動AIbot 引擎 語言%1 音量為%2',
        AIBOT_LCD_SHOW_STATUS: 'LCD屏在%1顯示%2',
        AIBOT_LOOP_STATE_CHANGE: '當 AIbot 狀態為 %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: '當 AIbot 收到激活信息 %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: '收到的 %1',
        AIBOT_LOOP_EMOTION: '當 AIbot 收到表情消息 %1 %2',
        GET_AIBOT_EMOTION_RESULT: '收到的表情代碼',
        AIBOT_EMOTION: '當前表情是否為 %1?',
        AIBOT_EMOTION_LIST: '表情包 %1',
        AIBOT_LOOP_CHAT_MESSAGE: '當 AIbot 收到聊天消息 %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: '收到消息的角色是 %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: '收到的消息內容',
        AIBOT_CONFIG_WEBSOCKET: '配置後台: %1',
        AIBOT_LOOP_MCP: '當 AIbot 收到 MCP 指令 %1 %2',

        AIBOT_WIFI_MANUAL: 'WIFI直連',
        AIBOT_WIFI_AUTO: '配網模式',
        AIBOT_BACKEND_XIAOZHI: '小智AI後台',
        AIBOT_BACKEND_KEYES: '科易AI後台',
        AIBOT_STATE_IDLE: '空閒中',
        AIBOT_STATE_INITTED: '已初始化',
        AIBOT_STATE_LOADING: '加載中',
        AIBOT_STATE_LOADING_FAILED: '加載失敗',
        AIBOT_STATE_STANDBY: '待命',
        AIBOT_STATE_CONNECTING: '連接中',
        AIBOT_STATE_LISTENING: '聆聽中',
        AIBOT_STATE_SPEAKING: '說話中',
        AIBOT_LCD_STATUS: '狀態框',
        AIBOT_LCD_EMOTION: '表情框',
        AIBOT_LCD_CHAT: '內容框',
        AIBOT_ACTIVATION_CODE: '激活碼',
        AIBOT_ACTIVATION_MESSAGE: '激活網址',
        AIBOT_EMOTION_HAPPY: '高興',
        AIBOT_EMOTION_COOL: '酷炫',
        AIBOT_EMOTION_LAUGHING: '大笑',
        AIBOT_EMOTION_FUNNY: '搞笑',
        AIBOT_EMOTION_SAD: '憂傷',
        AIBOT_EMOTION_ANGRY: '生氣',
        AIBOT_EMOTION_CRYING: '哭泣',
        AIBOT_EMOTION_LOVING: '喜歡',
        AIBOT_EMOTION_EMBARRASSED: '尷尬',
        AIBOT_EMOTION_SURPRISED: '驚訝',
        AIBOT_EMOTION_SHOCKED: '震驚',
        AIBOT_EMOTION_THINKING: '思考',
        AIBOT_EMOTION_WINKING: '調皮',
        AIBOT_EMOTION_RELAXED: '放鬆',
        AIBOT_EMOTION_DELICIOUS: '享受',
        AIBOT_EMOTION_KISSY: '親親',
        AIBOT_EMOTION_CONFIDENT: '自信',
        AIBOT_EMOTION_SLEEPY: '困倦',
        AIBOT_EMOTION_SILLY: '搞怪',
        AIBOT_EMOTION_CONFUSED: '困惑',
        AI_BOT_INIT_OLED: '初始化 OLED顯示屏 SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'OLED屏在%1顯示%2',
        AIBOT_WIFI_MODE_DIRECT: 'WIFI直連',
        AIBOT_WIFI_MODE_AUTO: '配網模式',
        AIBOT_OLED_STATUS_BOX: '狀態框',
        AIBOT_OLED_EMOTION_BOX: '表情框',
        AIBOT_OLED_CONTENT_BOX: '內容框',
        AIBOT_ACTIVATION_URL: '激活網址',
        AIBOT_ROLE_ASSISTANT: '助手',
        AIBOT_ROLE_USER: '用戶'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',
        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        KS_TIME_LABEL:'计时器',
        KS_MILLIS: '运行时间 (毫秒)',
        KS_MICROS: '运行时间 (微秒)',

        AIBOT_CATEGORY_INIT: '初始化',
        AIBOT_CATEGORY_EVENT: '事件',
        AIBOT_INIT_WIFI: '初始化AIbot WIFI 配网模式',
        AIBOT_INIT_MIC: 'I2S 麦克风 BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'I2S 扬声器 BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD 背光 %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: '启动AIbot 引擎 语言%1 音量为%2',
        AIBOT_LCD_SHOW_STATUS: 'LCD屏在%1显示%2',
        AIBOT_LOOP_STATE_CHANGE: '当 AIbot 状态为 %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: '当 AIbot 收到激活信息 %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: '收到的 %1',
        AIBOT_LOOP_EMOTION: '当 AIbot 收到表情消息 %1 %2',
        GET_AIBOT_EMOTION_RESULT: '收到的表情代码',
        AIBOT_EMOTION: '当前表情是否为 %1?',
        AIBOT_EMOTION_LIST: '表情包 %1',
        AIBOT_LOOP_CHAT_MESSAGE: '当 AIbot 收到聊天消息 %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: '收到消息的角色是 %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: '收到的消息内容',
        AIBOT_CONFIG_WEBSOCKET: '配置后台: %1',
        AIBOT_LOOP_MCP: '当 AIbot 收到 MCP 指令 %1 %2',

        AIBOT_WIFI_MANUAL: 'WIFI直连',
        AIBOT_WIFI_AUTO: '配网模式',
        AIBOT_BACKEND_XIAOZHI: '小智AI后台',
        AIBOT_BACKEND_KEYES: '科易AI后台',
        AIBOT_STATE_IDLE: '空闲中',
        AIBOT_STATE_INITTED: '已初始化',
        AIBOT_STATE_LOADING: '加载中',
        AIBOT_STATE_LOADING_FAILED: '加载失败',
        AIBOT_STATE_STANDBY: '待命',
        AIBOT_STATE_CONNECTING: '连接中',
        AIBOT_STATE_LISTENING: '聆听中',
        AIBOT_STATE_SPEAKING: '说话中',
        AIBOT_LCD_STATUS: '状态框',
        AIBOT_LCD_EMOTION: '表情框',
        AIBOT_LCD_CHAT: '内容框',
        AIBOT_ACTIVATION_CODE: '激活码',
        AIBOT_ACTIVATION_MESSAGE: '激活网址',
        AIBOT_EMOTION_HAPPY: '高兴',
        AIBOT_EMOTION_COOL: '酷炫',
        AIBOT_EMOTION_LAUGHING: '大笑',
        AIBOT_EMOTION_FUNNY: '搞笑',
        AIBOT_EMOTION_SAD: '忧伤',
        AIBOT_EMOTION_ANGRY: '生气',
        AIBOT_EMOTION_CRYING: '哭泣',
        AIBOT_EMOTION_LOVING: '喜欢',
        AIBOT_EMOTION_EMBARRASSED: '尴尬',
        AIBOT_EMOTION_SURPRISED: '惊讶',
        AIBOT_EMOTION_SHOCKED: '震惊',
        AIBOT_EMOTION_THINKING: '思考',
        AIBOT_EMOTION_WINKING: '调皮',
        AIBOT_EMOTION_RELAXED: '放松',
        AIBOT_EMOTION_DELICIOUS: '享受',
        AIBOT_EMOTION_KISSY: '亲亲',
        AIBOT_EMOTION_CONFIDENT: '自信',
        AIBOT_EMOTION_SLEEPY: '困倦',
        AIBOT_EMOTION_SILLY: '搞怪',
        AIBOT_EMOTION_CONFUSED: '困惑',
        AI_BOT_INIT_OLED: '初始化 OLED显示屏 SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'OLED屏在%1显示%2',
        AIBOT_WIFI_MODE_DIRECT: 'WIFI直连',
        AIBOT_WIFI_MODE_AUTO: '配网模式',
        AIBOT_OLED_STATUS_BOX: '状态框',
        AIBOT_OLED_EMOTION_BOX: '表情框',
        AIBOT_OLED_CONTENT_BOX: '内容框',
        AIBOT_ACTIVATION_URL: '激活网址',
        AIBOT_ROLE_ASSISTANT: '助手',
        AIBOT_ROLE_USER: '用户'
    });
    Object.assign(Blockly.ScratchMsgs.locales.it, {
        KS_VARIABLE_LABEL: 'Tipo di Variabile',
        KS_variables_declare: 'Dichiara %1 variabile numerica Tipo %2 Nome %3 Assegnata a %4',
        KS_variables_declare2: 'Dichiara %1 variabile stringa Tipo %2 Nome %3 Assegnata a %4',
        KS_variables_set: 'Imposta %1 variabile su %2',
        KS_variables_change: 'Imposta %1 modalità variabile %2',
        KS_variables_value: 'variabile %1',
        KS_variables_setString: 'Imposta %1 variabile stringa su %2',
        KS_global: 'Globale',
        KS_local: 'Locale',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',
        KS_TEXT_LABEL: 'TESTO',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',
        KS_LOGIC_LABEL: 'logica',
        KS_judge: '%1 %2 %3',
        KS_TIME_LABEL: 'Timer',
        KS_MILLIS: 'tempo di esecuzione (ms)',
        KS_MICROS: 'tempo di esecuzione (us)',
    
        AIBOT_CATEGORY_INIT: 'Init',
        AIBOT_CATEGORY_EVENT: 'Evento',
        AIBOT_INIT_WIFI: 'Init modalità di configurazione WIFI di AIbot',
        AIBOT_INIT_MIC: 'Microfono I2S BCLK %1 WS %2 DIN %3',
        AIBOT_INIT_AUDIO: 'Altoparlante I2S BCLK %1 WS %2 DOUT %3',
        AIBOT_INIT_LCD: 'LCD Retroilluminazione %1 MOSI %2 CLK %3 DC %4 RST %5 CS %6',
        AIBOT_START_ENGINE: 'Avvia motore AIbot lingua %1 volume %2',
        AIBOT_LCD_SHOW_STATUS: 'Schermo LCD Visualizza %2 su %1',
        AIBOT_LOOP_STATE_CHANGE: 'Quando Stato AIbot è %1 %2 %3',
        AIBOT_LOOP_ACTIVATION: 'Quando AIbot Riceve Info Attivazione %1 %2',
        GET_AIBOT_ACTIVATION_MESSAGE: 'Ricevuto %1',
        AIBOT_LOOP_EMOTION: 'Quando AIbot Riceve Messaggio Emozione %1 %2',
        GET_AIBOT_EMOTION_RESULT: 'Codice Emozione Ricevuto',
        AIBOT_EMOTION: 'L\'Emozione Corrente è %1?',
        AIBOT_EMOTION_LIST: 'Pacchetto Emozioni %1',
        AIBOT_LOOP_CHAT_MESSAGE: 'Quando AIbot Riceve Messaggio Chat %1 %2',
        AIBOT_LOOP_CHAT_MESSAGE_ROLE_VAR: 'Il Ruolo del Messaggio Ricevuto è %1?',
        AIBOT_LOOP_CHAT_MESSAGE_MSG_VAR: 'Contenuto del Messaggio Ricevuto',
        AIBOT_CONFIG_WEBSOCKET: 'Configura Backend: %1',
        AIBOT_LOOP_MCP: 'Quando AIbot Riceve Comando MCP %1 %2',
    
        AIBOT_WIFI_MANUAL: 'Connessione WIFI Diretta',
        AIBOT_WIFI_AUTO: 'Modalità Configurazione Rete',
        AIBOT_BACKEND_XIAOZHI: 'Backend AI Xiaozhi',
        AIBOT_BACKEND_KEYES: 'Backend AI Keyes',
        AIBOT_STATE_IDLE: 'Inattivo',
        AIBOT_STATE_INITTED: 'Inizializzato',
        AIBOT_STATE_LOADING: 'Caricamento',
        AIBOT_STATE_LOADING_FAILED: 'Caricamento Fallito',
        AIBOT_STATE_STANDBY: 'In Attesa',
        AIBOT_STATE_CONNECTING: 'Connessione',
        AIBOT_STATE_LISTENING: 'Ascolto',
        AIBOT_STATE_SPEAKING: 'Parlando',
        AIBOT_LCD_STATUS: 'Casella Stato',
        AIBOT_LCD_EMOTION: 'Casella Emozione',
        AIBOT_LCD_CHAT: 'Casella Contenuto',
        AIBOT_ACTIVATION_CODE: 'Codice Attivazione',
        AIBOT_ACTIVATION_MESSAGE: 'URL Attivazione',
        AIBOT_EMOTION_HAPPY: 'Felice',
        AIBOT_EMOTION_COOL: 'Cool',
        AIBOT_EMOTION_LAUGHING: 'Ridendo',
        AIBOT_EMOTION_FUNNY: 'Divertente',
        AIBOT_EMOTION_SAD: 'Triste',
        AIBOT_EMOTION_ANGRY: 'Arrabbiato',
        AIBOT_EMOTION_CRYING: 'Piangendo',
        AIBOT_EMOTION_LOVING: 'Amorevole',
        AIBOT_EMOTION_EMBARRASSED: 'Imbarazzato',
        AIBOT_EMOTION_SURPRISED: 'Sorpreso',
        AIBOT_EMOTION_SHOCKED: 'Scioccato',
        AIBOT_EMOTION_THINKING: 'Pensando',
        AIBOT_EMOTION_WINKING: 'Facendo l\'occhiolino',
        AIBOT_EMOTION_RELAXED: 'Rilassato',
        AIBOT_EMOTION_DELICIOUS: 'Delizioso',
        AIBOT_EMOTION_KISSY: 'Baciando',
        AIBOT_EMOTION_CONFIDENT: 'Fiducioso',
        AIBOT_EMOTION_SLEEPY: 'Assonnato',
        AIBOT_EMOTION_SILLY: 'Sciocco',
        AIBOT_EMOTION_CONFUSED: 'Confuso',
        AI_BOT_INIT_OLED: 'Inizializza Display OLED SDA %1 SCL %2',
        AIBOT_OLED_SHOW_STATUS: 'Schermo OLED Mostra %2 su %1',
        AIBOT_WIFI_MODE_DIRECT: 'Connessione WIFI Diretta',
        AIBOT_WIFI_MODE_AUTO: 'Modalità di Configurazione Rete',
        AIBOT_OLED_STATUS_BOX: 'Casella di Stato',
        AIBOT_OLED_EMOTION_BOX: 'Casella di Emozione',
        AIBOT_OLED_CONTENT_BOX: 'Casella di Contenuto',
        AIBOT_ACTIVATION_URL: 'URL di Attivazione',
        AIBOT_ROLE_ASSISTANT: 'Assistente',
        AIBOT_ROLE_USER: 'Utente'
    });
    return Blockly;
}
exports = addMsg;